### PR TITLE
Clusterbootstrap_controller should watch providers in core packages

### LINKED ISSUE #3477: Clusterbootstrap controller should watch providers in core packages
**Bug description**
Currently clusterbootstrap controller is watching providers in additional packages. It should be watching providers in both core and additional packages

**Affected product area (please put an X in all that apply)**

- ( ) APIs
- (x) Addons
- ( ) CLI
- ( ) Docs
- ( ) IAM
- ( ) Installation
- ( ) Plugin
- ( ) Security
- ( ) Test and Release
- ( ) User Experience
- ( ) Developer Experience

**Expected behavior**
Clusterbootstrap controller should watch providers in core packages

### PR DESCRIPTION
**Pull request by vijaykatam**
* Update watches to include providers in core packages

Signed-off-by: Vijay Katam <vkatam@vmware.com>

### What this PR does / why we need it

Update watches to include providers in core packages so that status updates are immediately propagated

### Which issue(s) this PR fixes

Fixes #3477 

### Describe testing done for PR

* Added env test

### Release note

```release-note
package based lcm: Clusterbootstrap_controller should watch providers in core packages
```

### CODE REVIEW

**Review by 12345lcr — APPROVED** [review]
Changes LGTM, thanks!

File: addons/controllers/clusterbootstrap_controller_test.go [hunk 1]
```diff
@@ -1029,6 +1029,127 @@ var _ = Describe("ClusterBootstrap Reconciler", func() {
...
+			clusterNamespace = "cluster-namespace-5"
+			clusterResourceFilePath = "testdata/test-cluster-bootstrap-5.yaml"
+			ns := &corev1.Namespace{
+				ObjectMeta: metav1.ObjectMeta{
+					Name: clusterNamespace,
+				},
+			}
+			err := k8sClient.Create(ctx, ns)
+			if err != nil {
+				Expect(apierrors.IsAlreadyExists(err)).To(BeTrue())
```
Comment (12345lcr) [inline addons/controllers/clusterbootstrap_controller_test.go:1048]: Since `BeforeEach` run on every start of `It`, perhaps combine the 2 `It` into 1 and separate with `By` can avoid this duplicate creation error?

Comment (vijaykatam) [reply addons/controllers/clusterbootstrap_controller_test.go:1048]: I combined the 2 tests into one.

**Review by maralavi — APPROVED** [review]
