### PR TITLE
Fix the imgpkg registy custom certificate validation and validation skipping issue

### LINKED ISSUE #1805: tkr-controller-manager tries to load cert even with TLS verification disabled
**Bug description**
tkr-controller-manager tries to load the cert even with TLS verificaiton is disabled (by using  --skip-verify-registry-cert=true or by exporting TKG_CUSTOM_IMAGE_REPOSITORY_SKIP_TLS_VERIFY=true)
**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [ ] Addons
- [ ] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Expected behavior**
tkr-controller-manager should not try to load cert if TLS verification disabled is disabled
**Steps to reproduce the bug**
Set caCerts key value to a base64 encoded corrupt/mangled certificate in the tkr-controller-config ConfigMap with caCerts key. Edit tkr-controller-manager deployment to set --skip-verify-registry-cert=True.

tkr-controller-manager pod should enter CrashLoopBackOff with the following error
```
2021-11-16T18:58:44.047Z ERROR setup problem running manager {"error": "failed to initialze registry client: Adding CA certificates from '/home/nonroot/registry_certs': failed", "errorVerbose": "Adding CA certificates from '/home/nonroot/registry_certs': failed\nfailed to initialze registry client\ngithub.com/vmware-tanzu/tanzu-framework/pkg/v1/tkr/pkg/registry.New\n\t/go/src/cayman-tanzu-framework/tanzu-framework/src/pkg/v1/tkr/pkg/registry/client.go:25\ngithub.com/vmware-tanzu/tanzu-framework/pkg/v1/tkr/controllers/source.(*reconciler).Start\n\t/go/src/cayman-tanzu-framework/tanzu-framework/src/pkg/v1/tkr/controllers/source/tkr_source_controller.go:493\nsigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).startLeaderElectionRunnables.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.14/pkg/manager/internal.go:473\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"}
github.com/go-logr/zapr.(*zapLogger).Error
 /go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
main.main
 /go/src/cayman-tanzu-framework/tanzu-framework/src/pkg/v1/tkr/main.go:93
runtime.main
 /usr/local/go/src/runtime/proc.go:225
```

**Version** (include the SHA if the version is not obvious)
v0.11.0
**Environment where the bug was observed (cloud, OS, etc)**

**Relevant Debug Output (Logs, manifests, etc)**

### PR DESCRIPTION
**Pull request by prkalle**
- Fixed the issue where imgpkg registry options were not being used during GetFile() and GetFiles()
  which caused certificate validation even though 'skip-verify-registry-cert' is set to true or
  custom ca cert is set.
- Also made changes in tkr-controller to add custom CA certs to the registry only if 'skip-verify-registry-cert' is set to false

Signed-off-by: PremKumar Kalle <pkalle@vmware.com>

### What this PR does / why we need it
This PR fixes the issue where imgpkg registry options were not being used during GetFile() and GetFiles()
which caused certificate validation even though 'skip-verify-registry-cert' is set to true orcustom ca cert is set.
### Which issue(s) this PR fixes

Fixes #1805, #1806

### Describe testing done for PR

Ran a local registry with self-signed certs and ran the TKR controller locally with `skip-verify-registry-cert=false` and the TKR controller failed with below errror which is expected
```
x509: certificate signed by unknown authority
```

Ran a local registry with self-signed certs and ran the TKR controller locally with `skip-verify-registry-cert=true` and the TKR controller ran successfully with out any cert issue. It successfully downloaded the tkr-compatibitility and tkrs.

Ran a local registry with self-signed certs and ran the TKR controller locally with `skip-verify-registry-cert=false` and custom image repositoy ca cert exported in `$HOME/regitry_certs` file and the TKR controller ran successfully with out any cert issue. It successfully downloaded the tkr-compatibitility and tkrs.

### Release note

```release-note
Fix the imgpkg registy custom certificate validation and validation skipping issue
```

### PR Checklist

- [ ] Squash the commits into one or a small number of logical commits
      
- [ ] Use good commit [messages](https://github.com/vmware-tanzu/tanzu-framework/blob/main/CONTRIBUTING.md)
- [ ] Ensure PR contains terms all contributors can understand and links all contributors can access

### CODE REVIEW

File: pkg/v1/tkr/controllers/source/tkr_source_controller.go [hunk 1]
```diff
@@ -524,10 +524,13 @@ func (r *reconciler) Start(ctx context.Context) error {
...
-	if err == nil {
-		if _, err = os.Stat(registryCertPath); err == nil {
-			r.registryOps.CACertPaths = []string{registryCertPath}
+	// Add custom CA cert paths only if VerifyCerts is enabled
+	if r.registryOps.VerifyCerts {
+		registryCertPath, err := getRegistryCertFile()
+		if err == nil {
+			if _, err = os.Stat(registryCertPath); err == nil {
+				r.registryOps.CACertPaths = []string{registryCertPath}
+			}
```
Comment (imikushin) [inline pkg/v1/tkr/controllers/source/tkr_source_controller.go:533]: Nice!

**Review by imikushin — APPROVED** [review]
LGTM. Thank you @prkalle!
