### PR TITLE
[release-0.25] Display correct error message when passing Cluster based resource without ClusterClass as part of cluster create

### LINKED ISSUE #3054: Add validation and throw proper error when Cluster resource without ClusterClass is passed with cluster create command
**Bug description**
Currently, when user passes Cluster resource as part of `tanzu cluster create --file <input.yaml>` and the cluster resource doesn't include ClusterClass as part of `.spec.topology.cluster` a wrong error message is thrown which can be misleading to the user.

As part of the error message, throw meaningful error message as this usecase is not yet supported.

**Affected product area (please put an X in all that apply)**

- ( ) APIs
- ( ) Addons
- ( ) CLI
- ( ) Docs
- ( ) IAM
- ( ) Installation
- ( ) Plugin
- ( ) Security
- ( ) Test and Release
- ( ) User Experience
- ( ) Developer Experience

**Expected behavior**
Should throw meaningful error message as this usecase is not yet supported.

**Steps to reproduce the bug**

**Version** (include the SHA if the version is not obvious)

**Environment where the bug was observed (cloud, OS, etc)**

**Relevant Debug Output (Logs, manifests, etc)**

### PR DESCRIPTION
**Pull request by anujc25**
### What this PR does / why we need it
- Display correct error message when passing Cluster based resource without ClusterClass as part of cluster create

Currently, when user passes `Cluster` resource as part of `tanzu cluster create --file <input.yaml>` and the cluster resource doesn't include ClusterClass as part of `.spec.topology.cluster` thrown proper error message.

### Which issue(s) this PR fixes

Fixes #3054

### Describe testing done for PR
- Added unit tests
- Manually verified by passing `--dry-run` output to `tanzu cluster create --file <manifest.yaml>` and verified the error message

### Release note

```release-note
Display correct error message when passing Cluster resource without ClusterClass as part of cluster create
```

### CODE REVIEW

**Review by saji-pivotal — APPROVED** [review]

File: pkg/v1/tkg/constants/clusterclass_mapping.go [hunk 1]
```diff
@@ -279,7 +279,8 @@ const (
 
 	SPEC = "spec"
 
-	TopologyClassIncorrectValueErrMsg = "input cluster class file, attribute spec.topology.class has no value or incorrect value or not following correct naming convension"
+	TopologyClassIncorrectValueErrMsg                = "input cluster class file, attribute spec.topology.class has no value or incorrect value or not following correct naming convention"
+	ClusterResourceWithoutTopologyNotSupportedErrMsg = "input file contains Cluster resource which doesn't have ClusterClass specified. Passing Cluster resource without ClusterClass specification is not supported"
```
Comment (vuil) [inline pkg/v1/tkg/constants/clusterclass_mapping.go:283]: this message will be surprising and misleading for providers that we have not turned on support for CC yet. let's think about being more selective on when we show it or at least improve on the error a little.

File: pkg/v1/tkg/tkgctl/helpers.go [hunk 2]
```diff
@@ -187,8 +188,13 @@ func CheckIfInputFileIsClusterClassBased(clusterConfigFile string) (bool, unstru
 	for i := range yamlObjects {
 		obj := yamlObjects[i]
 		if obj.GetKind() == constants.KindCluster {
-			isInputFileClusterClassBased = true
 			clusterObj = obj
+			class, exists, _ := unstructured.NestedString((&clusterObj).UnstructuredContent(), "spec", "topology", "class")
+			if exists && class != "" {
+				isInputFileClusterClassBased = true
+			} else {
+				return isInputFileClusterClassBased, clusterObj, errors.New(constants.ClusterResourceWithoutTopologyNotSupportedErrMsg)
```
Comment (vuil) [inline pkg/v1/tkg/tkgctl/helpers.go:196]: any reason why we need to return an error here? Seems like the caller would have the proper context to determined from the returned results to assess if it is an error or not.

**Comment by chandrareddyp** [comment]
LGTM!

**Review by vuil — APPROVED** [review]
