### PR TITLE
Address OOM kills in addons-manager

### LINKED ISSUE #2963: addons manager out of memory for ~ 200 clusters
**Bug description**

Addons manager is getting killed due to OOM in a scale test environment that has ~ 200 clusters.

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [x] Addons
- [ ] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Expected behavior**

Has enough memory for 200 clusters

**Steps to reproduce the bug**

Create 200 workload clusters in WCP

### PR DESCRIPTION
**Pull request by vijaykatam**
* Fewer concurrent reconciles for packageinstallstatus_controller
* Higher ratelimiting for packageinstallstatus_controller
* Bubble up errors in reconcile method so that retries back off
* Remove timestamp addition in status
* Allow enabling pprof
* [Fix memory leak]: Reassigning variables remote tracker client variable which is a pointer causes the object to be tracked in memory even after its usage.
* [Fix memory leak]: Remote tracker seems to be very sensitive with respect to how watch is called. Change watch to only include stateless functions.

Signed-off-by: Vijay Katam <vkatam@vmware.com>

### What this PR does / why we need it
Address OOM kills in addons-manager due to memory leaks

### Which issue(s) this PR fixes

Fixes #2963 

### Describe testing done for PR

Tested on a scale test cluster with 158 clusters. The pod has been running stable for over 7 hours without OOM.
```
k get pods -n vmware-system-tkg -o wide | grep addons
tanzu-addons-controller-manager-5b5658c9d6-sxzcz         1/1     Running   0               7h22m   10.102.0.2   420f40b588050e0ef6dd8503237a8f91   <none>           <none>
```
The memory stays around ~400 mb 
```
root@420f40b588050e0ef6dd8503237a8f91 [ ~ ]# curl http://localhost:18317/metrics | grep process_resident_memory_bytes
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 4.03750912e+08
100   97k    0   97k    0     0  38.9M      0 --:--:-- --:--:-- --:--:-- 47.7M
```

### Release note

```release-note
package-based-lcm: fix memory leaks in packageinstallstatus_controller
```

### Additional information
**Before fix** - notice packageinstallstatusreconciler

profile073

**After fix**  Note that packageinstallstatusreconciler does not show up anymore
profile122

### CODE REVIEW

File: addons/main.go [hunk 1]
```diff
@@ -378,11 +396,17 @@ func enableWebhooks(ctx context.Context, mgr ctrl.Manager, flags *addonFlags) {
...
+	// Exclude kapppkg.PackageInstall and kappdatapkg.Package from tracker caches to prevent too many items
+	// being held in memory along with standard ConfigMap and Secret
 	l := ctrl.Log.WithName("remote").WithName("ClusterCacheTracker")
-	tracker, err := capiremote.NewClusterCacheTracker(mgr, capiremote.ClusterCacheTrackerOptions{Log: &l})
+	tracker, err := capiremote.NewClusterCacheTracker(mgr, capiremote.ClusterCacheTrackerOptions{Log: &l,
+		ClientUncachedObjects: []client.Object{
+			&corev1.ConfigMap{},
+			&corev1.Secret{},
+			&kapppkg.PackageInstall{},
+			&kappdatapkg.Package{},
```
Comment (maralavi) [inline addons/main.go:407]: Why we add ```ConfigMap``` and ```Secret``` to the  ```ClientUncachedObjects```? We never read any of those types in PackageInstallStatusController code.

File: addons/main.go [hunk 2]
```diff
@@ -378,11 +396,17 @@ func enableWebhooks(ctx context.Context, mgr ctrl.Manager, flags *addonFlags) {
...
-	// we only read Package and PackageInstall resources through our cached client, we let those two resource types to be cached and we don't add any resource type to the ClientUncachedObjects list
+	// Exclude kapppkg.PackageInstall and kappdatapkg.Package from tracker caches to prevent too many items
+	// being held in memory along with standard ConfigMap and Secret
 	l := ctrl.Log.WithName("remote").WithName("ClusterCacheTracker")
-	tracker, err := capiremote.NewClusterCacheTracker(mgr, capiremote.ClusterCacheTrackerOptions{Log: &l})
+	tracker, err := capiremote.NewClusterCacheTracker(mgr, capiremote.ClusterCacheTrackerOptions{Log: &l,
+		ClientUncachedObjects: []client.Object{
+			&corev1.ConfigMap{},
+			&corev1.Secret{},
+			&kapppkg.PackageInstall{},
```
Comment (maralavi) [inline addons/main.go:406]: Wouldn't adding ```PackageInstall``` & ```Package``` to ```ClientUncachedObjects```, mean that we'll not allow objects of those types to be cached anymore? Does that mean that we will be reading from api server for those now and that we'll be not using the cache functionality of remote watch anymore?

File: addons/controllers/packageinstallstatus_controller.go [hunk 3]
```diff
@@ -297,13 +302,13 @@ func (r *PackageInstallStatusReconciler) reconcileClusterBootstrapStatus(
...
 	// we populate 'Message' with Carvel's PackageInstall 'UsefulErrorMessage' field as it contains more detailed information in case of an error
 	title := cases.Title(language.Und)
+	// skip adding current timestamp as it frequently triggers downstream controller to go through the CB resource for no reason
 	condition := clusterapiv1beta1.Condition{
 		Type: clusterapiv1beta1.ConditionType(title.String(pkgShortname)) + "-" +
 			clusterapiv1beta1.ConditionType(pkgiCondition.Type),
-		Status:             pkgiCondition.Status,
-		Message:            util.GetKappUsefulErrorMessage(pkgi.Status.UsefulErrorMessage),
-		Reason:             pkgiCondition.Reason,
-		LastTransitionTime: metav1.NewTime(time.Now().UTC().Truncate(time.Second)),
```
Comment (maralavi) [inline addons/controllers/packageinstallstatus_controller.go:306]: It's sad to see timestamp to go, it was adding more insight to the reconciliation status. But I can imagine it adds to the churn a lot as well

File: addons/controllers/csi/vspherecsiconfig_controller.go [hunk 4]
```diff
@@ -294,9 +294,6 @@ func (r *VSphereCSIConfigReconciler) reconcileVSphereCSIConfigNormal(ctx context
 		}
 	}
 
-	logger.Info(fmt.Sprintf("'%s' the secret '%s'", opResult,
```
Comment (vijaykatam) [inline addons/controllers/csi/vspherecsiconfig_controller.go:297]: This was causing lot of unnecessary logs

File: addons/controllers/packageinstallstatus_controller.go [hunk 5]
```diff
@@ -384,49 +381,19 @@ func (r *PackageInstallStatusReconciler) processPkgiIsManagedAndStatusChanged(o
...
-		// just log the error cause it is called from the predicate function with only bool return value
-		log.Error(err, "failed to determine whether the package is managed or not")
-		return false
-	}
-
-	return isManaged
-}
-
-// isPackageManaged checks if the provided PackageInstall is among the list of managed(core/additional) packages
-func (r *PackageInstallStatusReconciler) isPackageManaged(clusterObjKey client.ObjectKey, pkgiName string) (bool, error) {
```
Comment (vijaykatam) [inline addons/controllers/packageinstallstatus_controller.go:403]: Until we can find another way to address checking if a package is managed, I am removing this because it requires a client and putting a stateful function (one that has a ref to reconciler) is contributing towards memory leaks.

File: addons/controllers/packageinstallstatus_controller.go [hunk 6]
```diff
@@ -338,43 +335,43 @@ func (r *PackageInstallStatusReconciler) removeConditionIfExistsForPkgName(clust
 }
 
 // watchPackageInstalls sets a remote watch on the provided cluster on the Kind resource
-func (r *PackageInstallStatusReconciler) watchPackageInstalls(cluster *clusterapiv1beta1.Cluster, log logr.Logger) error {
+func watchPackageInstalls(ctx context.Context, watcher remote.Watcher, tracker *remote.ClusterCacheTracker, cluster *clusterapiv1beta1.Cluster, log logr.Logger) error {
```
Comment (vijaykatam) [inline addons/controllers/packageinstallstatus_controller.go:338]: I made these functions not receivers of the PackageInstallStatusReconciler because these are passed to Watch in the remote tracker and is contributing to memory leaks.

File: addons/controllers/packageinstallstatus_controller_test.go [hunk 7]
```diff
@@ -92,30 +92,31 @@ var _ = Describe("PackageInstallStatus Reconciler", func() {
...
-			mngClusterBootstrap := clusterBootstrapGet(client.ObjectKeyFromObject(mngCluster))
-			// Antrea is already installed into management cluster's tkg-system namespace
-			Expect(len(mngClusterBootstrap.Status.Conditions)).Should(Equal(1))
-			antreaCondType := "Antrea-" + clusterapiv1beta1.ConditionType(v1alpha1.ReconcileSucceeded)
-			Expect(mngClusterBootstrap.Status.Conditions[0].Type).Should(Equal(antreaCondType))
-			// install unmanaged package into workload cluster. Make sure cluster bootstrap conditions does not get changed fro un-managed package
-			installPackage(wlcCluster.Name, "pkg.test.carvel.dev.1.0.0", wlcCluster.Namespace)
-			wlcClusterBootstrap := clusterBootstrapGet(client.ObjectKeyFromObject(wlcCluster))
-			Expect(len(wlcClusterBootstrap.Status.Conditions)).Should(Equal(0))
+			//By("verifying un-managed packages do not update the 'Status.Conditions' for ClusterBootstrap")
```
Comment (vijaykatam) [inline addons/controllers/packageinstallstatus_controller_test.go:95]: we can restore this test after we figure out a better way to check managed packages.

File: addons/main.go [hunk 8]
```diff
@@ -378,11 +396,17 @@ func enableWebhooks(ctx context.Context, mgr ctrl.Manager, flags *addonFlags) {
 }
 
 func enablePackageInstallStatusController(ctx context.Context, mgr ctrl.Manager, flags *addonFlags) {
-	// set up a ClusterCacheTracker to provide to PackageInstallStatus controller which requires a connection to remote clusters
-	// the informers/caches are created only for objects accessed through Get/List in the code.
```
[the remark this answers is not in the document]
Comment (vijaykatam) [reply addons/main.go:382]: Added back with updated comment. Note that by default remote tracker excludes configmap and resource.

**Review by maralavi — APPROVED** [review]

File: addons/controllers/packageinstallstatus_controller.go [hunk 9]
```diff
@@ -205,12 +205,13 @@ func (r *PackageInstallStatusReconciler) reconcile(clusterClient client.Client,
 
 	var errorList []error
 
+	patchHelper, err := clusterapipatchutil.NewHelper(clusterBootstrap, r.Client)
+	if err != nil {
+		errorList = append(errorList, errors.Wrap(err, "error patching ClusterBootstrapStatus"))
+		retErr = kerrors.NewAggregate(errorList)
```
Comment (maralavi) [inline addons/controllers/packageinstallstatus_controller.go:211]: @vijaykatam This block needed to be outside of the defer, the tests were failing sue to this change.
