### PR TITLE
Consider additional metadata as part of kubernetes build version during version comparison 

### LINKED ISSUE #2292: Consider additional metadata as part of kubernetes build version during version comparison
**Bug description**
When using FIPS compliance Kubernetes version `v1.22.8+vmware.1-fips.1` during cluster upgrade kubernetes version verification fails with below error:
```
Verifying kubernetes version...
04:16:31 Error: kubernetes version verification failed: error while comparing kubernetes versions v1.22.8+vmware.1-fips.1, v1.22.8+vmware.1-fips.1: invalid version string
```

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [ ] Addons
- [x] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the SHA if the version is not obvious)

**Environment where the bug was observed (cloud, OS, etc)**

**Relevant Debug Output (Logs, manifests, etc)**

### PR DESCRIPTION
**Pull request by anujc25**
### What this PR does / why we need it
- Consider additional metadata as part of kubernetes build version during version comparison 
- Example: Consider `v1.17.3+vmware.1-fips.1` and `v1.17.3+vmware.2-fips.1` comparison

### Which issue(s) this PR fixes

Fixes #2292

### Describe testing done for PR
- Added unit tests

### Release note

```release-note
Consider additional metadata as part of kubernetes build version during version comparison
```

### PR Checklist

- [x] Squash the commits into one or a small number of logical commits
      
- [x] Use good commit [messages](https://github.com/vmware-tanzu/tanzu-framework/blob/main/CONTRIBUTING.md)
- [x] Ensure PR contains terms all contributors can understand and links all contributors can access

### CODE REVIEW

File: pkg/v1/tkg/utils/common_test.go [hunk 1]
```diff
@@ -413,6 +413,61 @@ var _ = Describe("CompareVMwareVersionStrings", func() {
 			Expect(err).To(MatchError("invalid version string"))
 		})
 	})
+
+	Context("When buildVersion includes more information about fips etc", func() {
```
Comment (vuil) [inline pkg/v1/tkg/utils/common_test.go:417]: nit: should you need to update to address the linter errors, instead of being so literal (fips...) in the Context.. line
maybe something along the lines of "when buildVersion includes -suffix ..".

**Review by vuil — APPROVED** [review]
lgtm

**Review by tenczar — APPROVED** [review]
LGTM

**Review by vuil — APPROVED** [review]

**Review by saji-pivotal — APPROVED** [review]
LGTM
