### PR TITLE
Plugin description wraps if its column exceeds 80 characters

### LINKED ISSUE #921: Tanzu plugin list should wrap description
**Bug description**
Running `tanzu plugin list` will show a list of current available/installed plugins, however the long description causes a change line which messed up the output. Please see the following screenshot:

Screen Shot 2021-10-19 at 12 31 04 PM

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [ ] Addons
- [x] CLI
- [ ] Docs
- [ ] Installation
- [x] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Expected behavior**

- All columns should support wrapping texts if they are too long.

**Steps to reproduce the bug**

- Run `tanzu plugin list`
- Without wide monitor (or resize your terminal window), you will see the output gets messed up.

**Version** (include the SHA if the version is not obvious)

- Latest tanzu framework build.

**Environment where the bug was observed (cloud, OS, etc)**

- Mac OS with iTerm2

**Relevant Debug Output (Logs, manifests, etc)**

### PR DESCRIPTION
**Pull request by codegold79**
Signed-off-by: F. Gold <fgold@vmware.com>

### What this PR does / why we need it

When descriptions are long and the terminal window is not/can not be resized to accommodate then, then the table formatting will be messed up. See corresponding issue to read more about the problem.

The fix is to enforce a description column width to be at most 80 characters (previously, it was 300 characters). It seems like a reasonable length for terminals to be resized to accommodate.

### Which issue(s) this PR fixes

Fixes #921 

### Describe testing done for PR

I built a plugin with a long description and ran `tanzu plugin list` with different output options. Here are what the outputs looked like:

```bash
$ tanzu plugin list
  NAME                DESCRIPTION                                                                       SCOPE       DISCOVERY      VERSION      STATUS     
  cluster             Kubernetes cluster operations                                                     Standalone  default-local  v0.19.0-dev  installed  
  feature             Operate on features and featuregates                                              Standalone  default-local  v0.19.0-dev  installed  
  kubernetes-release  Kubernetes release operations                                                     Standalone  default-local  v0.19.0-dev  installed  
  login               Login to the platform                                                             Standalone  default-local  v0.19.0-dev  installed  
  management-cluster  Kubernetes management cluster operations                                          Standalone  default-local  v0.19.0-dev  installed  
  package             Tanzu package management                                                          Standalone  default-local  v0.19.0-dev  installed  
  pinniped-auth       Pinniped authentication operations (usually not directly invoked)                 Standalone  default-local  v0.19.0-dev  installed  
  secret              Tanzu secret management                                                           Standalone  default-local  v0.19.0-dev  installed  
  builder             Build Tanzu components                                                            Standalone  admin-local    v0.19.0-dev  installed  
  codegen             Tanzu code generation tool                                                        Standalone  admin-local    v0.19.0-dev  installed  
  test                Test the CLI                                                                      Standalone  admin-local    v0.19.0-dev  installed  
  long-desc-plugin    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor    Standalone                 v0.0.1       installed  
                      incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis                                                           
                      nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.                                                        
                      Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu                                                      
                      fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in                                                       
                      culpa qui officia deserunt mollit anim id est laborum.                                                                               
$ tanzu plugin list -o table
  NAME                DESCRIPTION                                                                       SCOPE       DISCOVERY      VERSION      STATUS     
  cluster             Kubernetes cluster operations                                                     Standalone  default-local  v0.19.0-dev  installed  
  feature             Operate on features and featuregates                                              Standalone  default-local  v0.19.0-dev  installed  
  kubernetes-release  Kubernetes release operations                                                     Standalone  default-local  v0.19.0-dev  installed  
  login               Login to the platform                                                             Standalone  default-local  v0.19.0-dev  installed  
  management-cluster  Kubernetes management cluster operations                                          Standalone  default-local  v0.19.0-dev  installed  
  package             Tanzu package management                                                          Standalone  default-local  v0.19.0-dev  installed  
  pinniped-auth       Pinniped authentication operations (usually not directly invoked)                 Standalone  default-local  v0.19.0-dev  installed  
  secret              Tanzu secret management                                                           Standalone  default-local  v0.19.0-dev  installed  
  builder             Build Tanzu components                                                            Standalone  admin-local    v0.19.0-dev  installed  
  codegen             Tanzu code generation tool                                                        Standalone  admin-local    v0.19.0-dev  installed  
  test                Test the CLI                                                                      Standalone  admin-local    v0.19.0-dev  installed  
  long-desc-plugin    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor    Standalone                 v0.0.1       installed  
                      incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis                                                           
                      nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.                                                        
                      Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu                                                      
                      fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in                                                       
                      culpa qui officia deserunt mollit anim id est laborum.                                                                               
$ tanzu plugin list -o listtable
NAME:           cluster, feature, kubernetes-release, login, management-cluster, package, pinniped-auth, secret, builder, codegen, test, long-desc-plugin
DESCRIPTION:    Kubernetes cluster operations, Operate on features and featuregates, Kubernetes release operations, Login to the platform, Kubernetes management cluster operations, Tanzu package management, Pinniped authentication operations (usually not directly invoked), Tanzu secret management, Build Tanzu components, Tanzu code generation tool, Test the CLI, Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
SCOPE:          Standalone, Standalone, Standalone, Standalone, Standalone, Standalone, Standalone, Standalone, Standalone, Standalone, Standalone, Standalone
DISCOVERY:      default-local, default-local, default-local, default-local, default-local, default-local, default-local, default-local, admin-local, admin-local, admin-local, 
VERSION:        v0.19.0-dev, v0.19.0-dev, v0.19.0-dev, v0.19.0-dev, v0.19.0-dev, v0.19.0-dev, v0.19.0-dev, v0.19.0-dev, v0.19.0-dev, v0.19.0-dev, v0.19.0-dev, v0.0.1
STATUS:         installed, installed, installed, installed, installed, installed, installed, installed, installed, installed, installed, installed                                                                              
$ tanzu plugin list -o yaml
- description: Kubernetes cluster operations
  discovery: default-local
  name: cluster
  scope: Standalone
  status: installed
  version: v0.19.0-dev
- description: Operate on features and featuregates
  discovery: default-local
  name: feature
  scope: Standalone
  status: installed
  version: v0.19.0-dev
- description: Kubernetes release operations
  discovery: default-local
  name: kubernetes-release
  scope: Standalone
  status: installed
  version: v0.19.0-dev
- description: Login to the platform
  discovery: default-local
  name: login
  scope: Standalone
  status: installed
  version: v0.19.0-dev
- description: Kubernetes management cluster operations
  discovery: default-local
  name: management-cluster
  scope: Standalone
  status: installed
  version: v0.19.0-dev
- description: Tanzu package management
  discovery: default-local
  name: package
  scope: Standalone
  status: installed
  version: v0.19.0-dev
- description: Pinniped authentication operations (usually not directly invoked)
  discovery: default-local
  name: pinniped-auth
  scope: Standalone
  status: installed
  version: v0.19.0-dev
- description: Tanzu secret management
  discovery: default-local
  name: secret
  scope: Standalone
  status: installed
  version: v0.19.0-dev
- description: Build Tanzu components
  discovery: admin-local
  name: builder
  scope: Standalone
  status: installed
  version: v0.19.0-dev
- description: Tanzu code generation tool
  discovery: admin-local
  name: codegen
  scope: Standalone
  status: installed
  version: v0.19.0-dev
- description: Test the CLI
  discovery: admin-local
  name: test
  scope: Standalone
  status: installed
  version: v0.19.0-dev
- description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
    nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
    Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
    fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
    culpa qui officia deserunt mollit anim id est laborum.
  discovery: ""
  name: long-desc-plugin
  scope: Standalone
  status: installed
  version: v0.0.1
$ tanzu plugin list -o json
[
  {
    "description": "Kubernetes cluster operations",
    "discovery": "default-local",
    "name": "cluster",
    "scope": "Standalone",
    "status": "installed",
    "version": "v0.19.0-dev"
  },
  {
    "description": "Operate on features and featuregates",
    "discovery": "default-local",
    "name": "feature",
    "scope": "Standalone",
    "status": "installed",
    "version": "v0.19.0-dev"
  },
  {
    "description": "Kubernetes release operations",
    "discovery": "default-local",
    "name": "kubernetes-release",
    "scope": "Standalone",
    "status": "installed",
    "version": "v0.19.0-dev"
  },
  {
    "description": "Login to the platform",
    "discovery": "default-local",
    "name": "login",
    "scope": "Standalone",
    "status": "installed",
    "version": "v0.19.0-dev"
  },
  {
    "description": "Kubernetes management cluster operations",
    "discovery": "default-local",
    "name": "management-cluster",
    "scope": "Standalone",
    "status": "installed",
    "version": "v0.19.0-dev"
  },
  {
    "description": "Tanzu package management",
    "discovery": "default-local",
    "name": "package",
    "scope": "Standalone",
    "status": "installed",
    "version": "v0.19.0-dev"
  },
  {
    "description": "Pinniped authentication operations (usually not directly invoked)",
    "discovery": "default-local",
    "name": "pinniped-auth",
    "scope": "Standalone",
    "status": "installed",
    "version": "v0.19.0-dev"
  },
  {
    "description": "Tanzu secret management",
    "discovery": "default-local",
    "name": "secret",
    "scope": "Standalone",
    "status": "installed",
    "version": "v0.19.0-dev"
  },
  {
    "description": "Build Tanzu components",
    "discovery": "admin-local",
    "name": "builder",
    "scope": "Standalone",
    "status": "installed",
    "version": "v0.19.0-dev"
  },
  {
    "description": "Tanzu code generation tool",
    "discovery": "admin-local",
    "name": "codegen",
    "scope": "Standalone",
    "status": "installed",
    "version": "v0.19.0-dev"
  },
  {
    "description": "Test the CLI",
    "discovery": "admin-local",
    "name": "test",
    "scope": "Standalone",
    "status": "installed",
    "version": "v0.19.0-dev"
  },
  {
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "discovery": "",
    "name": "long-desc-plugin",
    "scope": "Standalone",
    "status": "installed",
    "version": "v0.0.1"
  }
]
```

### Release note

```release-note
    Plugin descriptions in plugin list table output wraps after 80 characters.
```

### PR Checklist

- [x] Squash the commits into one or a small number of logical commits
      
- [x] Use good commit [messages](https://github.com/vmware-tanzu/tanzu-framework/blob/main/CONTRIBUTING.md)
- [x] Ensure PR contains terms all contributors can understand and links all contributors can access

### CODE REVIEW

**Review by stmcginnis — APPROVED** [review]
Thanks, looks great to me. Will wait to let others take a look, but I think this is a good change.

File: pkg/v1/cli/component/output.go [hunk 1]
```diff
@@ -14,8 +14,10 @@ import (
 	"gopkg.in/yaml.v2"
 )
 
-const colWidth = 300
-const indentation = `  `
+const (
+	colWidth    = 80
```
Comment (navidshaikh) [inline pkg/v1/cli/component/output.go:18]: Some guides recommend to set it to 79 (just to be on safe side?) - for example [pep8](https://peps.python.org/pep-0008/#maximum-line-length)

80 is fine as well I think.

**Review by navidshaikh — APPROVED** [review]

File: pkg/v1/cli/component/output.go (hunk 1 above)
Comment (stmcginnis) [reply pkg/v1/cli/component/output.go:18]: I agree. If we want to be concerned about 80 (or 79) characters, then we should probably consider the entire line of output and not just the one column. So the limit would end up being more like the 30-50 range like you suggest.

I think this at least makes it a reasonable width, so I think this is definite improvement.

**Review by anujc25 — APPROVED** [review]
