### PR TITLE
replace 'username' and 'password' fields with secret reference in vspherecsiconfig api

### LINKED ISSUE #2115: VsphereCSIConfig API should not expose username/password as string
**Bug description**
VsphereCSIConfig API should not expose username/password as string. It needs to be a secret (corev1.TypedLocalObjectReference) similar to: https://github.com/vmware-tanzu/tanzu-framework/blob/main/apis/cpi/v1alpha1/vspherecpiconfig_types.go#L95
 
**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [x] Addons
- [ ] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the SHA if the version is not obvious)

**Environment where the bug was observed (cloud, OS, etc)**

**Relevant Debug Output (Logs, manifests, etc)**

### PR DESCRIPTION
**Pull request by peterochodo**
### What this PR does / why we need it
- replacing 'username' & 'password' fields in vspherecsiconfig api with reference to secret object that holds those credentials

### Which issue(s) this PR fixes

Fixes #2115 

### Describe testing done for PR

- Unit tests included. They run successfully.

### Release note

```release-note
package-based-lcm:
- when supplying non-paravirtual csi configuration via VSphereCSIConfig api, the fields "username" and "password" have been replaced by a reference to a secret that holds username and password information.
```

### PR Checklist

- [ ] Squash the commits into one or a small number of logical commits
      
- [ ] Use good commit [messages](https://github.com/vmware-tanzu/tanzu-framework/blob/main/CONTRIBUTING.md)
- [ ] Ensure PR contains terms all contributors can understand and links all contributors can access

### CODE REVIEW

File: addons/controllers/csi/vspherecsiconfig_utils.go [hunk 1]
```diff
@@ -205,7 +207,10 @@ func (r *VSphereCSIConfigReconciler) mapCSIConfigToProviderServiceAccount(cluste
 	return serviceAccount
 }
 
-func overrideDerivedValues(dvscsi *DataValuesVSphereCSI, config *csiv1alpha1.NonParavirtualConfig) { // nolint:gocyclo
+func (r *VSphereCSIConfigReconciler) overrideDerivedValues(ctx context.Context,
+	dvscsi *DataValuesVSphereCSI,
+	vcsiConfig *csiv1alpha1.VSphereCSIConfig) error { // nolint:gocyclo
```
Comment (danniel1205) [inline addons/controllers/csi/vspherecsiconfig_utils.go:212]: question: Are there any reason we want to skip gocyclo linter ? Usually we do not want to skip any linter checks unless we have to.

Comment (peterochodo) [reply addons/controllers/csi/vspherecsiconfig_utils.go]: - the linter flags a 'cyclomatic complexity' error for this function because it has more than 15 possible code paths. If you examine what the function is going, it examines 20+ fields for existence and takes one of two actions depending on the result. In theory, this indeed creates the possibility of more than 15 code paths. 

- However, it simplifies our code greatly to localize this conditional code to just this one function. Writing 3 functions to do what this one function is doing is not elegant.

Comment (danniel1205) [reply addons/controllers/csi/vspherecsiconfig_utils.go]: Thanks for the explanation. We had the same situation before, and https://github.com/vmware-tanzu/tanzu-framework/pull/1784/files is one PR we had to reduce the complexity. Would it be possible that we make the similar fix ? If not, could you help add some inline comments around the `// nolint: gocyclo` to explain why we need skip the linter ? Thanks.

Comment (peterochodo) [reply addons/controllers/csi/vspherecsiconfig_utils.go]: removed linter exception & refactored code

**Comment by danniel1205** [comment]
Suggestion: this PR lgtm, it would be great if you could help add some tests data in test-cluster-bootstrap-1.yaml similar to what CPI does ? Thanks.
- https://github.com/vmware-tanzu/tanzu-framework/blob/main/addons/controllers/testdata/test-cluster-bootstrap-1.yaml#L125
- https://github.com/vmware-tanzu/tanzu-framework/blob/main/addons/controllers/testdata/test-cluster-bootstrap-1.yaml#L163
- https://github.com/vmware-tanzu/tanzu-framework/blob/main/addons/controllers/testdata/test-cluster-bootstrap-1.yaml#L253
- https://github.com/vmware-tanzu/tanzu-framework/blob/main/addons/controllers/testdata/test-cluster-bootstrap-1.yaml#L246
- https://github.com/vmware-tanzu/tanzu-framework/blob/main/addons/controllers/testdata/test-cluster-bootstrap-1.yaml#L1038
- https://github.com/vmware-tanzu/tanzu-framework/blob/main/addons/controllers/testdata/test-cluster-bootstrap-1.yaml#L1076

**Comment by peterochodo** [comment]
> 

done

**Comment by peterochodo** [comment]
> Suggestion: this PR lgtm, it would be great if you could help add some tests data in test-cluster-bootstrap-1.yaml similar to what CPI does ? Thanks.
> 
> * https://github.com/vmware-tanzu/tanzu-framework/blob/main/addons/controllers/testdata/test-cluster-bootstrap-1.yaml#L125
> * https://github.com/vmware-tanzu/tanzu-framework/blob/main/addons/controllers/testdata/test-cluster-bootstrap-1.yaml#L163
> * https://github.com/vmware-tanzu/tanzu-framework/blob/main/addons/controllers/testdata/test-cluster-bootstrap-1.yaml#L253
> * https://github.com/vmware-tanzu/tanzu-framework/blob/main/addons/controllers/testdata/test-cluster-bootstrap-1.yaml#L246
> * https://github.com/vmware-tanzu/tanzu-framework/blob/main/addons/controllers/testdata/test-cluster-bootstrap-1.yaml#L1038
> * https://github.com/vmware-tanzu/tanzu-framework/blob/main/addons/controllers/testdata/test-cluster-bootstrap-1.yaml#L1076

done

**Review by danniel1205 — APPROVED** [review]
lgtm
