### PR TITLE
CAPV aggregated role patch appends rbac rules

### LINKED ISSUE #2594: CAPV aggregated role rules being overwritten by 2 controllers
**Bug description**

vspherecpiconfig_controller and vspherecsiconfig_controller patch CAPV aggregated role rules but they end up overwriting each other causing issues like 

```
E0608 22:57:38.243262       1 serviceaccount_controller.go:218] capv-controller-manager/providerserviceaccount-controller/test-vds-ns/kiran-tkc-nx7wp "msg"="Error ensuring provider serviceaccounts" "error"="unable to create role for provider serviceaccount kiran-tkc-nx7wp-pvcsi: roles.rbac.authorization.k8s.io \"kiran-tkc-nx7wp-pvcsi\" is forbidden: user \"system:serviceaccount:vmware-system-capw:default\" (groups=[\"system:serviceaccounts\" \"system:serviceaccounts:vmware-system-capw\" \"system:authenticated\"]) is attempting to grant RBAC permissions not currently held:\n{APIGroups:[\"cns.vmware.com\"], Resources:[\"cnscsisvfeaturestates\"], Verbs:[\"get\" \"list\" \"watch\"]}\n{APIGroups:[\"cns.vmware.com\"], Resources:[\"cnsfileaccessconfigs\"], Verbs:[\"get\" \"list\" \"watch\" \"update\" \"create\" \"delete\"]}\n{APIGroups:[\"cns.vmware.com\"], Resources:[\"cnsvolumemetadatas\"], Verbs:[\"get\" \"list\" \"watch\" \"update\" \"create\" \"delete\"]}"
E0608 22:57:38.245334       1 controller.go:317] controller/providerserviceaccount "msg"="Reconciler error" "error"="unable to create role for provider serviceaccount kiran-tkc-nx7wp-pvcsi: roles.rbac.authorization.k8s.io \"kiran-tkc-nx7wp-pvcsi\" is forbidden: user \"system:serviceaccount:vmware-system-capw:default\" (groups=[\"system:serviceaccounts\" \"system:serviceaccounts:vmware-system-capw\" \"system:authenticated\"]) is attempting to grant RBAC permissions not currently held:\n{APIGroups:[\"cns.vmware.com\"], Resources:[\"cnscsisvfeaturestates\"], Verbs:[\"get\" \"list\" \"watch\"]}\n{APIGroups:[\"cns.vmware.com\"], Resources:[\"cnsfileaccessconfigs\"], Verbs:[\"get\" \"list\" \"watch\" \"update\" \"create\" \"delete\"]}\n{APIGroups:[\"cns.vmware.com\"], Resources:[\"cnsvolumemetadatas\"], Verbs:[\"get\" \"list\" \"watch\" \"update\" \"create\" \"delete\"]}" "name"="kiran-tkc-nx7wp" "namespace"="test-vds-ns" "reconciler group"="vmware.infrastructure.cluster.x-k8s.io" "reconciler kind"="ProviderServiceAccount"
^[[A^[[A^C"
```
**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [x] Addons
- [ ] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Expected behavior**
Rules should not be overwritten

### PR DESCRIPTION
**Pull request by vijaykatam**
* Fix patching rbac rules of capv aggregated cluster role.

Signed-off-by: Vijay Katam <vkatam@vmware.com>

### What this PR does / why we need it

vspherecpiconfig_controller and vspherecsiconfig_controller patch CAPV aggregated role rules but they end up overwriting each other

### Which issue(s) this PR fixes

Fixes: #2594 

### Describe testing done for PR

1. Env tests
2. Tested with supervisor cluster

### Release note

```release-note
package-based-lcm: Fix patching rbac rules of capv aggregated cluster role
```

### PR Checklist

- [x] Squash the commits into one or a small number of logical commits
      
- [x] Use good commit [messages](https://github.com/vmware-tanzu/tanzu-framework/blob/main/CONTRIBUTING.md)
- [x] Ensure PR contains terms all contributors can understand and links all contributors can access

### CODE REVIEW

File: addons/controllers/cpi/vspherecpiconfig_controller.go [hunk 1]
```diff
@@ -175,8 +175,9 @@ func (r *VSphereCPIConfigReconciler) reconcileVSphereCPIConfigNormal(ctx context
 	if *cpiConfig.Spec.VSphereCPI.Mode == VSphereCPIParavirtualMode {
 		// create an aggregated cluster role RBAC that will be inherited by CAPV (https://kubernetes.io/docs/reference/access-authn-authz/rbac/#aggregated-clusterroles)
 		// CAPV needs to hold these rules before it can grant it to serviceAccount for CPI
+
 		_, err := controllerutil.CreateOrPatch(ctx, r.Client, constants.CAPVAggregatedClusterRole, func() error {
-			constants.CAPVAggregatedClusterRole.Rules = providerServiceAccountRBACRules
+			constants.CAPVAggregatedClusterRole.Rules = append(constants.CAPVAggregatedClusterRole.Rules, providerServiceAccountRBACRules...)
```
Comment (shyaamsn) [inline addons/controllers/cpi/vspherecpiconfig_controller.go:180]: dumb question: Since we are using **constants**.CAPVAggregatedClusterRole doesnt it mutate this var everytime the controller runs ?

i.e. first run it adds providerServiceAccountRBACRules and second time this run doesnt it append again ?

Comment (vijaykatam) [reply addons/controllers/cpi/vspherecpiconfig_controller.go:180]: yup it does but controllerutil.CreateOrPatch does the diff before applying

**Review by shyaamsn — APPROVED** [review]
LGTM
