### PR TITLE
fix deleting management cluster clean up avi resource error in long latency condition

### LINKED ISSUE #2330: When deleting management cluster in a high latency env, clean up avi resources could cause error
**Bug description**

When trying to delete the management cluster in a really poor networking condition, clean up avi resources failed and cause management cluster deletion to fail.

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [ ] Addons
- [x] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Expected behavior**

- Management cluster got deleted successfully

**Steps to reproduce the bug**

run `tanzu mc delete` in a high-latency env, clean up avi resources step will fail

**Version** (include the SHA if the version is not obvious)

**Environment where the bug was observed (cloud, OS, etc)**

- cloud provider: vSphere
- OS: Linux

**Relevant Debug Output (Logs, manifests, etc)**

### PR DESCRIPTION
**Pull request by XudongLiuHarold**
Signed-off-by: Xudong Liu <xudongl@vmware.com>

### What this PR does / why we need it

Fix when the network condition is poor, clean up avi resources could cause the management cluster deletion failed error.

### Which issue(s) this PR fixes

Fixes #2330

### Describe testing done for PR

- launched vSphere testbed, create and delete management cluster several times to verify this change, and test passed. 

### Release note

```release-note
deleting management cluster can run successfully even in high latency network env.
```

### PR Checklist

- [x] Squash the commits into one or a small number of logical commits
      
- [x] Use good commit [messages](https://github.com/vmware-tanzu/tanzu-framework/blob/main/CONTRIBUTING.md)
- [x] Ensure PR contains terms all contributors can understand and links all contributors can access

### CODE REVIEW

**Comment by alfredthenarwhal** [comment]
> @XudongLiuHarold:  /test install-vc7
Commit: 669d2f0

Tests failed! Build no: 1947

File: pkg/v1/tkg/client/delete_region.go [hunk 1]
```diff
@@ -470,15 +470,11 @@ func (c *TkgClient) waitForAVIResourceCleanup(regionalClusterClient clusterclien
 		if apierrors.IsNotFound(err) {
 			return nil
 		}
-		return errors.Wrapf(err, "unable to get ako statefulset")
```
Comment (HanFa) [inline pkg/v1/tkg/client/delete_region.go:473]: why should we remove this line? if statefulset fails to be get

File: pkg/v1/tkg/client/delete_region.go [hunk 2]
```diff
@@ -470,15 +470,11 @@ func (c *TkgClient) waitForAVIResourceCleanup(regionalClusterClient clusterclien
...
 	}
 	if err := regionalClusterClient.WaitForAVIResourceCleanUp(constants.AkoStatefulSetName, constants.AkoNamespace); err != nil {
-		// losing connection should be consider as AVI resources clean up finished.
-		// TODO: (xudongl) Any ideas how to make this line cleaner? Thanks.
-		if strings.Contains(err.Error(), "dial tcp") {
-			return nil
+		if !strings.Contains(err.Error(), "dial tcp") {
+			log.Error(err, "clean up AVI resources error")
```
Comment (sbhatp) [inline pkg/v1/tkg/client/delete_region.go:476]: This will cause cluster-deletion to continue even though AKO is stuck in resource deletion.

Did we decide to use IsServiceUnavailable() instead?

File: pkg/v1/tkg/client/delete_region.go (hunk 1 above)
Comment (XudongLiuHarold) [reply pkg/v1/tkg/client/delete_region.go:473]: It is possible that once we set the `deleteConfig` to be true, the AVI resources have been cleaned up immediately. 
If we also use AVI to provide control plane HA, in that case, we may not get the ako statefulset using the client because of network issue.

File: pkg/v1/tkg/clusterclient/clusterclient.go [hunk 3]
```diff
@@ -634,7 +634,12 @@ func (c *client) WaitForAutoscalerDeployment(deploymentName, namespace string) e
 }
 
 func (c *client) WaitForAVIResourceCleanUp(statefulSetName, namespace string) error {
-	return c.GetResource(&appsv1.StatefulSet{}, statefulSetName, namespace, VerifyAVIResourceCleanupFinished, &PollOptions{Interval: CheckResourceInterval, Timeout: AVIResourceCleanupTimeout})
+	err := c.GetResource(&appsv1.StatefulSet{}, statefulSetName, namespace, VerifyAVIResourceCleanupFinished, &PollOptions{Interval: CheckResourceInterval, Timeout: AVIResourceCleanupTimeout})
+	// retry once when network condition is poor
+	if apierrors.IsServiceUnavailable(err) {
+		return c.GetResource(&appsv1.StatefulSet{}, statefulSetName, namespace, VerifyAVIResourceCleanupFinished, &PollOptions{Interval: CheckResourceInterval, Timeout: AVIResourceCleanupTimeout})
```
Comment (HanFa) [inline pkg/v1/tkg/clusterclient/clusterclient.go:640]: do we have something better like `Eventually` to do this?

**Review by HanFa — APPROVED** [review]

File: pkg/v1/tkg/clusterclient/clusterclient.go (hunk 3 above)
Comment (sbhatp) [reply pkg/v1/tkg/clusterclient/clusterclient.go:640]: +1
Retrying once may not be helpful as the next attempt will happen within milliseconds.

Comment (XudongLiuHarold) [reply pkg/v1/tkg/clusterclient/clusterclient.go:640]: I believe that `GetResource` function is already did what you suggest here, it will keep trying until time out

Comment (sbhatp) [reply pkg/v1/tkg/clusterclient/clusterclient.go:640]: Got it

File: pkg/v1/tkg/client/delete_region.go (hunk 1 above)
Comment (sbhatp) [reply pkg/v1/tkg/client/delete_region.go:473]: We should log a warning for easier debugging

**Review by sbhatp — APPROVED** [review]

**Comment by alfredthenarwhal** [comment]
> @XudongLiuHarold:  /test install-vc7
Commit: 8f3b777

Tests failed! Build no: 2026

**Comment by danniel1205** [comment]
I know this change has been tested from the bot comment, thanks for having it tested. Could you also help updating the PR description by adding something in `Describe testing done for PR` ?

**Review by anujc25 — APPROVED** [review]
