### PR TITLE
Handle `context-aware-cli-for-plugin` feature flag with `tanzu init` …

### LINKED ISSUE #1411: `tanzu init` and `tanzu update` command doesn't respect `context-aware-cli-for-plugins` feature flag
**Bug description**

`tanzu init` and `tanzu update` command doesn't respect `context-aware-cli-for-plugins` feature flag. 

This allows unpredictable behavior of tanzu cli because running this command tries to install old plugins sometimes with `tanzu init` from GCP bucket depending on the `repositories` configuration under config file.

Running `tanzu update` tries to download tanzu-cli from the GCP bucket.

As when `context-aware-cli-for-plugins` feature flag is enabled, tanzu cli doesn't rely on GCP bucket or the `repositories` configuration under config.yaml file, it should not download and install plugins from GCP bucket. 

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [ ] Addons
- [x] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Expected behavior**

- `tanzu init` will sync/update all available plugins for the user based on `context-aware-cli-for-plugin` feature
- `tanzu update` should not rely on the GCP bucket when `context-aware-cli-for-plugin` feature flag is enabled

**Steps to reproduce the bug**

- Run below commands:
- `tanzu init`
- `tanzu update`

**Version** (include the SHA if the version is not obvious)
v0.14.0

**Environment where the bug was observed (cloud, OS, etc)**

**Relevant Debug Output (Logs, manifests, etc)**

### PR DESCRIPTION
**Pull request by anujc25**
…and `tanzu update` commands

### What this PR does / why we need it

- `tanzu init` will sync/update all available plugins for the user based on `context-aware-cli-for-plugin` feature
- `tanzu update` command is not supported when `context-aware-cli-for-plugin` feature flag is enabled. This is to avoid relying on the GCP bucket to download the core and plugin binaries as we don't want to rely on the GCP bucket when `context-aware-cli-for-plugins` feature flag is enabled.
- 
### Which issue(s) this PR fixes

Fixes #1411

### Release note

```release-note
Fix `tanzu init` and `tanzu update` command not respecting `context-aware-cli-for-plugins` feature flag
```

### PR Checklist

- [x] Squash the commits into one or a small number of logical commits
      
- [x] Use good commit [messages](https://github.com/vmware-tanzu/tanzu-framework/blob/main/CONTRIBUTING.md)
- [x] Ensure PR contains terms all contributors can understand and links all contributors can access

### CODE REVIEW

File: pkg/v1/cli/command/core/update.go [hunk 1]
```diff
@@ -31,6 +32,12 @@ var updateCmd = &cobra.Command{
 		"group": string(cliv1alpha1.SystemCmdGroup),
 	},
 	RunE: func(cmd *cobra.Command, args []string) error {
+		if config.IsFeatureActivated(config.FeatureContextAwareCLIForPlugins) {
+			// TODO: Implement inline update of tanzu CLI when `context-aware-cli-for-plugins` feature flag is enabled
+			log.Warning("Updating CLI and plugins is not supported when `context-aware-cli-for-plugins` feature flag is enabled")
```
Comment (vuil) [inline pkg/v1/cli/command/core/update.go:37]: The log message may not make sense to users especially now that the feature is activated by default.
Maybe something like:

log.Warning("CLI self-update is currently not support. For updating plugins please use the `plugin sync` command")

File: pkg/v1/cli/command/core/update.go [hunk 2]
```diff
@@ -31,6 +32,11 @@ var updateCmd = &cobra.Command{
 		"group": string(cliv1alpha1.SystemCmdGroup),
 	},
 	RunE: func(cmd *cobra.Command, args []string) error {
+		if config.IsFeatureActivated(config.FeatureContextAwareCLIForPlugins) {
+			log.Warning("CLI self-update is currently not support. For updating plugins please use the `tanzu plugin sync` command")
```
Comment (vuil) [inline pkg/v1/cli/command/core/update.go:36]: nit: support -> supported.
also, should it return an error instead of nil?

**Review by vuil — APPROVED** [review]
lgtm, thanks!

**Comment by alfredthenarwhal** [comment]
> @vuil:  /test install-vc7
Commit: a748ef5

Tests passed! Build no: 1264
