### PR TITLE
Temporary hack to configure tkr-source-controller package values

### LINKED ISSUE #2567: tkr-source-controller package values are not configured
**Bug description**

GetTKGPackageConfigValuesFileFromUserConfig used to configure the package values needed ton install the tkg package is missing logic to obtain values required by the tkr-source-controller sub package.

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [ ] Addons
- [x] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [x] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Expected behavior**
tkr-source-controller package to be installed with correct values

**Steps to reproduce the bug**
Create management cluster with pblcm feature flag, observe that the tkr-source-controller is not deployed with the correct parameters

**Version** (include the SHA if the version is not obvious)

**Environment where the bug was observed (cloud, OS, etc)**

**Relevant Debug Output (Logs, manifests, etc)**

### PR DESCRIPTION
**Pull request by prkalle**
Temporary hack to configure tkr-source-controller package values

Signed-off-by: PremKumar Kalle <pkalle@vmware.com>

### What this PR does / why we need it
Temporary hack to set tkr-source-controller configuration during tkg package installation.
TKR source controller requires the URLs to be configured to fetch the bom/bom-meta-data/tkr packages. This can fetched from the tkg-bom file. While the fix to retreive the configuration values from tkg-bom and configure the tkr-source-controller package values is being worked on , this PR address the issue with temporary fix by hardcoding these values for a specific version.
### Which issue(s) this PR fixes

Fixes #2567 

### Describe testing done for PR

Tested locally and could see the tkr-source-controller came up successfully and the TKRs are installed and workload cluster was also created successfully (we still need to use the gist to install the TKR initially as we have the chicken-egg issue which is worked out separately)

### Release note 

```release-note
None
```

### PR Checklist

- [ ] Squash the commits into one or a small number of logical commits
      
- [ ] Use good commit [messages](https://github.com/vmware-tanzu/tanzu-framework/blob/main/CONTRIBUTING.md)
- [ ] Ensure PR contains terms all contributors can understand and links all contributors can access

### CODE REVIEW

**Review by vuil — APPROVED** [review]
some nits:
- linter on comment, 
- use a shorter title for commit, use additional lines to provide better description
- use None for release notes if none provided.

but otherwise lgtm, thanks!

File: pkg/v1/tkg/managementcomponents/helper.go [hunk 1]
```diff
@@ -22,6 +22,18 @@ const (
 
 // GetTKGPackageConfigValuesFileFromUserConfig returns values file from user configuration
 func GetTKGPackageConfigValuesFileFromUserConfig(managementPackageVersion string, userProviderConfigValues map[string]string) (string, error) {
+	//Temporary hack for TKR source controller paths
```
Comment (vuil) [inline pkg/v1/tkg/managementcomponents/helper.go:25]: Please added a TODO: and reference the issue if any used to track the work to populate the values correctly from the bom data.

**Review by imikushin — APPROVED** [review]
LGTM!
