### PR TITLE
Missing flag from isolated-cluster plugin

### LINKED ISSUE #4150: Isolated-cluster: --destination-insecure flag on the wrong command
**Bug description**

For the new `isolated-cluster` plugin, grom what I can tell, the `--destination-insecure` flag should be for the `upload-bundle` command. However, it is instead showing on the `download-bundle` command.

**Affected product area (please put an X in all that apply)**

- ( ) APIs
- ( ) Addons
- ( ) CLI
- ( ) Docs
- ( ) IAM
- (x) Installation
- (x) Plugin
- ( ) Security
- ( ) Test and Release
- ( ) User Experience
- ( ) Developer Experience

**Expected behavior**

The `--destination-insecure` command should be on the `upload-bundle` command.

**Steps to reproduce the bug**

Notice the presence of a `--destination-insecure` flag on the `download-bundle` command:
```
$ tanzu isolated-cluster download-bundle -h
Download images/bundle into local disk as TAR

Usage:
  tanzu isolated-cluster download-bundle [flags]

Flags:
      --destination-insecure           Trusts the server certificate without validating it (optional)
  -h, --help                           help for download-bundle
      --source-ca-certificate string   The private repository’s CA certificate  (optional)
      --source-insecure                Trusts the server certificate without validating it (optional)
      --source-repo string             OCI repo where TKG bundles or images are hosted (required) (default "projects.registry.vmware.com/tkg")
      --tkg-version string             TKG version (required)
```
and notice there is no `--destination-insecure` flag for the `upload-bundle` command

```
./isolated-cluster upload-bundle -h
Upload images to private repository.

Usage:
  tanzu isolated-cluster upload-bundle [flags]

Flags:
      --destination-ca-certificate string   The private repository’s CA certificate  (optional)
      --destination-repo string             Private OCI repository where the images should be hosted in air-gapped (required)
  -h, --help                                help for upload-bundle
      --source-directory string             Path to the directory that contains the TAR file  (required)

```

**Version** (include the SHA if the version is not obvious)

Today's main: 84cc3e591

**Environment where the bug was observed (cloud, OS, etc)**

Locally

It was an easy fix so I'll post a PR.

cc @Vandy-P

### PR DESCRIPTION
**Pull request by marckhouzam**
### What this PR does / why we need it

For the new isolated-cluster plugin the flag `--destination-insecure` was being added to the `download-bundle` command instead of having it on the `upload-bundle` command.

Also, the `--source-directory` flag was meant to be required but was not due to a copy/paste error.

Also, the `--source-repo` flag should not be marked required since it has a documented default value.  This point needs to be confirmed, as we could instead remove the default value and possibly add it to the help text.  I will put a comment in-line to discuss this.

Finally, some spelling errors were present.

This commit fixes the above issues.

### Which issue(s) this PR fixes

Fixes #4150 

### Describe testing done for PR

Apply the PR and check the help of both sub-commands of the `isolated-cluster` plugin and make sure
the `--destination-insecure` flag is on the `upload-bundle` command.

```
$ tanzu isolated-cluster upload-bundle -h
Upload images to private repository.

Usage:
  tanzu isolated-cluster upload-bundle [flags]

Flags:
      --destination-ca-certificate string   The private repository’s CA certificate  (optional)
      --destination-insecure                Trusts the private repository’s certificate without validating it (optional)
      --destination-repo string             Private OCI repository where the images should be hosted in air-gapped (required)
  -h, --help                                help for upload-bundle
      --source-directory string             Path to the directory that contains the TAR file  (required)

$ tanzu isolated-cluster download-bundle -h
Download images/bundle into local disk as TAR

Usage:
  tanzu isolated-cluster download-bundle [flags]

Flags:
  -h, --help                           help for download-bundle
      --source-ca-certificate string   The private repository’s CA certificate  (optional)
      --source-insecure                Trusts the server certificate without validating it (optional)
      --source-repo string             OCI repo where TKG bundles or images are hosted (default "projects.registry.vmware.com/tkg")
      --tkg-version string             TKG version (required)
```

Also test that `--source-directory` is required:
```
$ tanzu isolated-cluster upload-bundle
Error: required flag(s) "destination-repo", "source-directory" not set
```
Also test that `--source-repo` is no longer required:
```
$ tanzu isolated-cluster download-bundle
Error: required flag(s) "tkg-version" not set
```

cc @Vandy-P

### CODE REVIEW

File: cmd/cli/plugin/isolated-cluster/imageop/publishimagestotar.go [hunk 1]
```diff
@@ -42,8 +42,7 @@ var PublishImagestotarCmd = &cobra.Command{
 }
 
 func init() {
-	PublishImagestotarCmd.Flags().StringVarP(&pullImage.TkgImageRepo, "source-repo", "", "projects.registry.vmware.com/tkg", "OCI repo where TKG bundles or images are hosted (required)")
-	_ = PublishImagestotarCmd.MarkFlagRequired("source-repo")
```
Comment (marckhouzam) [inline cmd/cli/plugin/isolated-cluster/imageop/publishimagestotar.go:46]: I believe the `--source-repo` flag should not be required since it has a default value.  
If we want it to be required, we should remove the default value since it shows in help and is therefore confusing to the user (why have a default value but force me to specify my own value?).

If the goal is to require the flag but guide the user by showing the TKG repo URI, we should instead add it in the help text of the flag instead of as a default value.

Comment (marckhouzam) [reply cmd/cli/plugin/isolated-cluster/imageop/publishimagestotar.go:46]: @Vandy-P Does this make sense?

Comment (Vandy-P) [reply cmd/cli/plugin/isolated-cluster/imageop/publishimagestotar.go:46]: @marckhouzam  Yes correct , we should  remove require flag.

**Review by Vandy-P — APPROVED** [review]

**Comment by randomvariable** [comment]
The behaviour of
```
   --destination-ca-certificate string   The private repository’s CA certificate  (optional)
    --destination-insecure                Trusts the private repository’s certificate without validating it (optional)
```
is still wrong, but happy to have it in a separate issue/PR.

I'd like to see these reverted to `--ca-certificate` and `--insecure` as per the original design. `--ca-certificate` is currently required if `--insecure` is not set since the command does not use the system trust store at all, which makes it unusable on MacOS and Windows, and only by specifying a distro specific path to the CA trust store for Linux.

**Comment by randomvariable** [comment]
Filed https://github.com/vmware-tanzu/tanzu-framework/issues/4173

**Comment by Vandy-P** [comment]
Hi @randomvariable  , I am creating a new PR for CA cert issue 
https://github.com/vmware-tanzu/tanzu-framework/pull/4168

**Comment by vuil** [comment]
Thanks for filing 4173 @randomvariable . This should be good to go in that case..

**Review by vuil — APPROVED** [review]
Thanks for the fix, lgtm.
