### PR TITLE
Allow only trusted registries and fix issue regarding installing plugins in internet restricted from OCI source

### LINKED ISSUE #1504: Allow only trusted registries when installing plugins from OCI source
**Bug description**

Currently, the `tanzu plugin sync` command and a few other commands automatically download the plugin to the user's machine without much information. This makes a good user experience as users don't have to worry about manually downloading plugins when they log in, create or upgrade management cluster.

Add validation to only allow certain trusted registries when downloading plugins from the OCI registry.

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [ ] Addons
- [x] CLI
- [ ] Docs
- [ ] IAM
- [x] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Expected behavior**
Throw an error when an untrusted registry is used when downloading plugins.

**Steps to reproduce the bug**

**Version** (include the SHA if the version is not obvious)

**Environment where the bug was observed (cloud, OS, etc)**

**Relevant Debug Output (Logs, manifests, etc)**

### PR DESCRIPTION
**Pull request by anujc25**
### What this PR does / why we need it
- This PR adds verification regarding the source of the OCI image which we are downloading plugin binary.
- This change will only allow registries that are trusted by default or provided with the `ALLOWED_REGISTRY` environment variable.

### Which issue(s) this PR fixes

Fixes #1504, #1505

### Describe testing done for PR
- Manual testing with different combinations of default registry, custom registry, and allows-registry env variable
- Added unit tests

### Release note

```release-note
Allow only trusted registries when installing plugins from OCI source
Fixed issue regarding installing plugins on internet restricted environment from OCI source
```

### PR Checklist

- [x] Squash the commits into one or a small number of logical commits
      
- [x] Use good commit [messages](https://github.com/vmware-tanzu/tanzu-framework/blob/main/CONTRIBUTING.md)
- [x] Ensure PR contains terms all contributors can understand and links all contributors can access

### CODE REVIEW

File: pkg/v1/tkr/pkg/registry/client.go [hunk 1]
```diff
@@ -160,3 +165,27 @@ func getAllFilesContentFromImage(image regv1.Image) (map[string][]byte, error) {
 
 	return nil, errors.New("cannot find file from the image")
 }
+
+// DownloadBundle downloads OCI bundle similar to `imgpkg pull -b` command
+// It is recommended to use this function when downloading imgpkg bundle
+func (r *registry) DownloadBundle(imageName, outputDir string) error {
+	// Creating a dummy writer to capture the logs
+	// currently this logs are not displays or used directly
```
Comment (vuil) [inline pkg/v1/tkr/pkg/registry/client.go:173]:
```suggestion
	// currently this logs are not displayed or used directly
```

File: pkg/v1/tkr/pkg/registry/client.go [hunk 2]
```diff
@@ -160,3 +165,27 @@ func getAllFilesContentFromImage(image regv1.Image) (map[string][]byte, error) {
 
 	return nil, errors.New("cannot find file from the image")
 }
+
+// DownloadBundle downloads OCI bundle similar to `imgpkg pull -b` command
+// It is recommended to use this function when downloading imgpkg bundle
```
Comment (vuil) [inline pkg/v1/tkr/pkg/registry/client.go:170]: nit: perhaps adding the reason(s) behind it would be useful.

File: pkg/v1/cli/pluginmanager/manager.go [hunk 3]
```diff
@@ -702,3 +708,31 @@ func getPluginDescriptorResource(pluginFilePath string) (*cliv1alpha1.PluginDesc
 	}
 	return &pd, nil
 }
+
+// verifyPlugin verifies the authenticity of the plugin source
```
Comment (vuil) [inline pkg/v1/cli/pluginmanager/manager.go:712]: nit: saying we are verifying for authenticity is probably a stretch.
```suggestion
// verifyPlugin verifies the plugin source is allowed to be used
```
We can update the comment once the implementation changes.

**Review by vuil — COMMENTED** [review]
thanks, just a few small comments.

**Review by vuil — APPROVED** [review]
Lgtm, thanks!
