### PR TITLE
Read config variable from mgmt cluster into cleanup cluster when deleting mgmt cluster

### LINKED ISSUE #3420: Delete clusterclass management cluster on vSphere fails when reconciling tkg-clusterclass-vsphere packageInstall
**Bug description**
Create a management cluster with ClusterClass, delete the management cluster. It will failed with error
**Affected product area (please put an X in all that apply)**

- ( ) APIs
- ( ) Addons
- ( ) CLI
- ( ) Docs
- ( ) IAM
- ( ) Installation
- ( ) Plugin
- ( ) Security
- ( ) Test and Release
- ( ) User Experience
- ( ) Developer Experience

**Expected behavior**

**Steps to reproduce the bug**
Create a management cluster with ClusterClass, delete the management cluster. It will failed with below error

```
failure while installing TKG management package: resource reconciliation failed: I0912 20:57:00.497973      27 request.go:665] Waited for 1.001631443s due to client-side throttling, not priority and fairness, request: GET:https://100.64.0.1:443/apis/clusterctl.cluster.x-k8s.io/v1alpha3?timeout=32s
kapp: Error: waiting on reconcile packageinstall/tkg-clusterclass (packaging.carvel.dev/v1alpha1) namespace: tkg-system:
  Finished unsuccessfully (Reconcile failed:  (message: Error (see .status.usefulErrorMessage for details))). Reconcile failed: Error (see .status.usefulErrorMessage for details)
```

The packageInstall tkg-clusterclass is failing because of tkg-clusterclass-vsphere is failing

```
  Observed Generation:     1
  Useful Error Message:    I0912 21:07:33.841750     221 request.go:665] Waited for 1.03032229s due to client-side throttling, not priority and fairness, request: GET:https://100.64.0.1:443/apis/addons.cluster.x-k8s.io/v1alpha4?timeout=32s
kapp: Error: waiting on reconcile packageinstall/tkg-clusterclass-vsphere (packaging.carvel.dev/v1alpha1) namespace: tkg-system:
  Finished unsuccessfully (Reconcile failed:  (message: Error (see .status.usefulErrorMessage for details)))
  Version:  0.21.0
Events:     <none>
kubo@7itfFS7UMBgM6:~${code}
Checking the packageInstall tkg-clusterclass-vsphere on the *Kind* cluster, it has below error
{code:java}
Spec:
  Package Ref:
    Ref Name:  tkg-clusterclass-vsphere.tanzu.vmware.com
    Version Selection:
      Prereleases:
  Service Account Name:  tanzu-infra-clusterclass-package-sa
  Values:
    Secret Ref:
      Name:  tkg-clusterclass-infra-values
Status:
  Conditions:
    Message:               Error (see .status.usefulErrorMessage for details)
    Status:                True
    Type:                  ReconcileFailed
  Friendly Description:    Reconcile failed: Error (see .status.usefulErrorMessage for details)
  Last Attempted Version:  0.21.0
  Observed Generation:     1
  Useful Error Message:    I0912 21:00:57.934198     173 request.go:665] Waited for 1.037242838s due to client-side throttling, not priority and fairness, request: GET:https://100.64.0.1:443/apis/run.tanzu.vmware.com/v1alpha1?timeout=32s
kapp: Error: Applying create vspheremachinetemplate/tkg-vsphere-control-plane (infrastructure.cluster.x-k8s.io/v1beta1) namespace: tkg-system:
  Creating resource vspheremachinetemplate/tkg-vsphere-control-plane (infrastructure.cluster.x-k8s.io/v1beta1) namespace: tkg-system:
    API server says:
      VSphereMachineTemplate.infrastructure.cluster.x-k8s.io "tkg-vsphere-control-plane" is invalid: spec.template.spec.template:
        Invalid value: "": spec.template.spec.template in body should be at least 1 chars long (reason: Invalid)
  Version:  0.21.0
Events:     <none>
The tkg-clusterclass-vsphere packageinstall failed. It expect the `VSPHERE_TEMPLATE` in as input
```
It's kind of strange because creating cluster it doesn't report this error and VSPHERE_TEMPLATE is not provided.
 

**Version** (include the SHA if the version is not obvious)

**Environment where the bug was observed (cloud, OS, etc)**

**Relevant Debug Output (Logs, manifests, etc)**

### PR DESCRIPTION
**Pull request by ydp**
### What this PR does / why we need it

When deleting management cluster, fetch tkg-tkp-tkg-system-values from mgmt cluster and configure it onto the cleanup cluster before install management packages.

### Which issue(s) this PR fixes

Fixes #3420 

### Release note

```release-note

```

### CODE REVIEW

File: pkg/v1/tkg/client/delete_region.go [hunk 1]
```diff
@@ -152,7 +152,8 @@ func (c *TkgClient) DeleteRegion(options DeleteRegionOptions) error { //nolint:f
 
 		// If clusterclass feature flag is enabled then deploy management components
 		if config.IsFeatureActivated(config.FeatureFlagPackageBasedLCM) {
-			if err = c.InstallOrUpgradeManagementComponents(cleanupClusterKubeconfigPath, "", false); err != nil {
+			if err = c.InstallManagementComponentsInCleanupCluster(cleanupClusterKubeconfigPath,
```
Comment (DanielXiao) [inline pkg/v1/tkg/client/delete_region.go:155]: I think we have 2 options to avoid change to many code:

1. Retrieve all key/values from secret tkg-pkg-tkg-system-values and set them to `c.TKGConfigReaderWriter()` before we call `c.InstallOrUpgradeManagementComponents`.
2. Add a parameter `tkgPackageValuesFile` to `c.InstallOrUpgradeManagementComponents` allowing overwrite `tkgpackagevalues.yaml`

Comment (ydp) [reply pkg/v1/tkg/client/delete_region.go:155]: Thank you @DanielXiao  for the review, I will refactor the commit per our discussion offline.

File: tkg/client/delete_region.go [hunk 2]
```diff
@@ -152,6 +152,15 @@ func (c *TkgClient) DeleteRegion(options DeleteRegionOptions) error { //nolint:f
 
 		// If clusterclass feature flag is enabled then deploy management components
 		if config.IsFeatureActivated(config.FeatureFlagPackageBasedLCM) {
+			// Read config variable from management cluster and set it into cleanup cluster
+			configValues, err := c.getUserConfigVariableValueMapForUpgrade(regionContext.SourceFilePath, regionContext.ContextName)
```
Comment (DanielXiao) [inline tkg/client/delete_region.go:156]: Maybe we can refactor the method name to `getUserConfigVariableValueMapFromManagementCluster`. `ForUpgrade` is a bit confusing.

Comment (ydp) [reply tkg/client/delete_region.go:156]: Thank you @DanielXiao for reviewing, yes, `ForUpgrade` is indeed make no sense now, considering the mgmt cluster context is just a parameter, maybe using `getUserConfigVariableValueMapFromSecret` or `getUserConfigVariableValueMapFromCluster` comparing to the other one that's getting them from config file, and I see similar naming methods used in clusterclient.go

Comment (DanielXiao) [reply tkg/client/delete_region.go:156]: Yes, `getUserConfigVariableValueMapFromSecret` looks good

Comment (ydp) [reply tkg/client/delete_region.go]: Addressed

**Review by DanielXiao — APPROVED** [review]

**Review by wjun — APPROVED** [review]
LGTM
