### PR TITLE
Fix GVR lookup errors seen in Kind cluster during mgmt cluster bootstrap

### LINKED ISSUE #2708: ClusterBootstrapController fails to find resources
**Bug description**
failed to getGVR" "error"="unable to find server preferred resource cpi.tanzu.vmware.com/VsphereCPIConfig"

- [x] APIs
- [x] Addons
- [ ] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Expected behavior**
Clone succeeds when there is a resource

**Environment where the bug was observed (cloud, OS, etc)**
Kind cluster that @vuil has
**Relevant Debug Output (Logs, manifests, etc)**
```
clusterbootstrapclone.go:438] ClusterBootstrapController "msg"="failed to getGVR" "error"="unable to find server preferred resource cpi.tanzu.vmware.com/VsphereCPIConfig"
clusterbootstrapclone.go:209] ClusterBootstrapController "msg"="unable to clone secrets or providers" "error"="unable to find server preferred resource cpi.tanzu.vmware.com/VsphereCPIConfig"
controller.go:317] controller/cluster "msg"="Reconciler error" "error"="unable to find server preferred resource cpi.tanzu.vmware.com/VsphereCPIConfig" "name"="tkg-mgmt-vsphere-20220620234107" "namespace"="tkg-system" "reconciler group"="cluster.x-k8s.io" "reconciler kind"="Cluster"
**Affected product area (please put an X in all that apply)**
```

### PR DESCRIPTION
**Pull request by vijaykatam**
Fix GVR lookup errors seen in Kind cluster during mgmt cluster bootstrap

Signed-off-by: Vijay Katam <vkatam@vmware.com>

### What this PR does / why we need it

Fixes an issue where a kind cluster used for bootstrapping mgmt cluster is
encountering issues with GVR lookup during provider ref cloning by moving
GVR lookup to a centralized helper so that clone helper can reuse caching. No errors
from controller which has a map for caching prev results.

### Which issue(s) this PR fixes

Fixes #2708

### Describe testing done for PR
1. Added unit tests
2. Tested on supervisor cluster

### Release note

```release-note
package-based-lcm: Fix GVR lookup errors seen in Kind cluster during mgmt cluster bootstrap
```

### PR Checklist

- [x] Squash the commits into one or a small number of logical commits
      
- [x] Use good commit [messages](https://github.com/vmware-tanzu/tanzu-framework/blob/main/CONTRIBUTING.md)
- [x] Ensure PR contains terms all contributors can understand and links all contributors can access

### CODE REVIEW

**Review by maralavi — APPROVED** [review]

**Comment by maralavi** [comment]
LGTM. Thanks for the PR.

File: addons/controllers/clusterbootstrap_controller.go [hunk 1]
```diff
@@ -1174,6 +1139,8 @@ func (r *ClusterBootstrapReconciler) GetDataValueSecretNameFromBootstrapPackage(
 				return packageSecretName, nil
 			}
 		}
+		// cbPkg.ValuesFrom is nil and not TKGS
+		return "", nil
 	}
 
 	// When valuesFrom is not nil, but either valuesFrom.Inline, valuesFrom.SecretRef, or valuesFrom.providerRef is empty or nil,
```
Comment (maralavi) [inline addons/controllers/clusterbootstrap_controller.go:1146]: @vijaykatam , I think I should have removed this part and just return nil here. This section seems unreachable to me

Comment (vijaykatam) [reply addons/controllers/clusterbootstrap_controller.go:1146]: We need a catch all to return an error otherwise the func won't compile.

**Review by danniel1205 — APPROVED** [review]
lgtm, thanks for the pr
