### PR TITLE
Suppress provider update if developer needs

### LINKED ISSUE #4187: Ytt overlay customization check should be skipped for yttcc and yttcb
**Bug description**

Related to [TKG-15856]( https://jira.eng.vmware.com/browse/TKG-15856)
The purpose of the checksum check is to detect modifications to legacy overlays that could possibly impact the accuracy of the legacy-to-CC translation of a cluster creation attempt using a legacy configuration file.
However, now, checkSum func is checking all ytt files. This causes some users create a classy based cluster with yttcc customizations will be fail.
We should allow users to create classy cluster with yttcc customizations. So we should skip yttcc and yttcb customizations check. That means we have below scenarios:
- If a user does ytt customizations, but user doesn't set allow-legacy-cluster to be true, then we will report error;
- If a user does ytt customizations, but user has set allow-legacy-cluster to be true, go to create legacy based cluster;
- If a user does yttcc or yttcb customizations, we should go to create classy cluster (by default) or legacy cluster (if allow-legacy-cluster is true).

**Affected product area (please put an X in all that apply)**

- ( ) APIs
- ( ) Addons
- ( ) CLI
- ( ) Docs
- ( ) IAM
- ( ) Installation
- ( ) Plugin
- ( ) Security
- ( ) Test and Release
- ( ) User Experience
- ( ) Developer Experience

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the SHA if the version is not obvious)

**Environment where the bug was observed (cloud, OS, etc)**

**Relevant Debug Output (Logs, manifests, etc)**

### PR DESCRIPTION
**Pull request by xiujuanx**
### What this PR does / why we need it

For our internal development, sometimes, we need to update ytt/yttcc/yttcb template, and test if our changes work.
Also we don't want to build the whole things so that we can save more time for developing. In this situation, we can set SUPPRESS_PROVIDERS_UPDATE env var, and create legacy or classy cluster depends on yourself.

### Which issue(s) this PR fixes

Fixes #4187 

### Release note

```release-note

```

### CODE REVIEW

File: tkg/client/common.go [hunk 1]
```diff
@@ -364,11 +365,14 @@ func (c *TkgClient) ShouldDeployClusterClassBasedCluster(isManagementCluster boo
 		return true, nil
 	}
 
+	// Ignore the checksum check if config variable 'SUPPRESS_PROVIDERS_UPDATE' is set.
+	isSuppressProvidersUpdateSet := os.Getenv(constants.SuppressProvidersUpdate) != ""
```
Comment (12345lcr) [inline tkg/client/common.go:369]: May I ask why the `SUPPRESS_PROVIDERS_UPDATE` was required to set to number `1` instead of boolean or other values? Does this number contain any meaning?

Comment (xiujuanx) [reply tkg/client/common.go:369]: @12345lcr , no, `SUPPRESS_PROVIDERS_UPDATE` can be set to any string. As long as it is not an empty string, then `isSuppressProvidersUpdateSet` will be `true`.

**Review by 12345lcr — APPROVED** [review]

**Review by wjun — APPROVED** [review]

**Review by imikushin — APPROVED** [review]
