### PR TITLE
getGVR should only fail if no GroupVersionResource is found

### LINKED ISSUE #4460: ClusterBootstrap Webhook deny create request if any API service is not available
**Bug description**
If not all gvr are available at the clusterbootrap create validation, the webhook erronously denies the request. 

**Affected product area (please put an X in all that apply)**

- ( ) APIs
- ( x) Addons
- ( ) CLI
- ( ) Docs
- ( ) IAM
- ( ) Installation
- ( ) Plugin
- ( ) Security
- ( ) Test and Release
- ( ) User Experience
- ( ) Developer Experience

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the SHA if the version is not obvious)

**Environment where the bug was observed (cloud, OS, etc)**

**Relevant Debug Output (Logs, manifests, etc)**

### PR DESCRIPTION
**Pull request by adduarte**
The call to ServerPreferredResources could return an err != nil even though the resource list is not empty.

getGVR should not report a failure if the resource list does contain a matching GroupVersionResource, even if ServerPreferredResources returned err != nil.

### What this PR does / why we need it
This patch modifies  getGVR so it  only return a error (failure) if it cannot find a matching GroupVersionResource. 
### Which issue(s) this PR fixes

Fixes #4460

### Describe testing done for PR

Unit test created and executed.
ran deployed to vsphere 7 platform. 

### Release note

```release-note
Fixes bug in clusterbootstrap webhook which incorrectly failed create validation if not all api service endpoints are running at the time of creation.
```

### CODE REVIEW

File: addons/webhooks/clusterbootstrap_webhook.go [hunk 1]
```diff
@@ -292,7 +292,12 @@ func (wh *ClusterBootstrap) getGVR(gk schema.GroupKind) (*schema.GroupVersionRes
 	}
 	apiResourceList, err := wh.cachedDiscoveryClient.ServerPreferredResources()
 	if err != nil {
-		return nil, err
+		if apiResourceList == nil {
+			return nil, err
+		}
```
Comment (adduarte) [inline addons/webhooks/clusterbootstrap_webhook.go:297]: The comment by codecov is incorrect. The lines are covered by test added in this patch. Verified by stepping through with debugger

File: addons/webhooks/clusterbootstrap_webhook.go [hunk 2]
```diff
@@ -292,7 +292,12 @@ func (wh *ClusterBootstrap) getGVR(gk schema.GroupKind) (*schema.GroupVersionRes
...
+		if _, ok := err.(*discovery.ErrGroupDiscoveryFailed); !ok {
+			return nil, err
+		}
```
Comment (adduarte) [inline addons/webhooks/clusterbootstrap_webhook.go:300]: The comment by codecov is incorrect. The lines are covered by test added in this patch. Verified by stepping through with debugger

File: addons/webhooks/clusterbootstrap_webhook.go [hunk 3]
```diff
@@ -292,7 +292,12 @@ func (wh *ClusterBootstrap) getGVR(gk schema.GroupKind) (*schema.GroupVersionRes
 	}
 	apiResourceList, err := wh.cachedDiscoveryClient.ServerPreferredResources()
 	if err != nil {
-		return nil, err
+		if apiResourceList == nil {
```
Comment (adduarte) [inline addons/webhooks/clusterbootstrap_webhook.go:295]: I think we can skip this check since we do iterate over apiResourceList further down the code. and if apiresourceList == nil, we return an error there.

File: addons/webhooks/clusterbootstrap_webhook.go [hunk 4]
```diff
@@ -291,7 +291,7 @@ func (wh *ClusterBootstrap) getGVR(gk schema.GroupKind) (*schema.GroupVersionRes
 		return gvr, nil
 	}
 	apiResourceList, err := wh.cachedDiscoveryClient.ServerPreferredResources()
-	if err != nil {
+	if _, ok := err.(*discovery.ErrGroupDiscoveryFailed); err != nil && !ok {
```
Comment (adduarte) [inline addons/webhooks/clusterbootstrap_webhook.go:294]: if the error is ErrGroupDiscoveryFailed, we can safely continue, since an apiresult == nil will be catch later down the code and we will return the correct result if we don't find what we are looking for in the contents of apiresult

**Review by shyaamsn — COMMENTED** [review]
LGTM

File: addons/webhooks/clusterbootstrap_webhook.go (hunk 4 above)
Comment (maralavi) [reply addons/webhooks/clusterbootstrap_webhook.go:296]: Since you didn't check the error on line 293, wouldn't the following cast fail in case of err==nil?
```err.(*discovery.ErrGroupDiscoveryFailed)````

Comment (adduarte) [reply addons/webhooks/clusterbootstrap_webhook.go:296]: no. I checked by running this code
```func main() {
	var err error
	if _, ok := err.(*discovery.ErrGroupDiscoveryFailed); !ok && err != nil {
		println("Error is not be ")
	}
	if err == nil {
		println("Error is nil")
	}
}

Comment (maralavi) [reply addons/webhooks/clusterbootstrap_webhook.go:296]: Agreed, you are right, ```ok``` captures that case here

**Comment by alfredthenarwhal** [comment]
> @adduarte:  /test install-vc7
Commit: 9a52c4c

Tests failed! Build no: 4398

**Comment by alfredthenarwhal** [comment]
> @adduarte:  /test install-vc7
Commit: 9a52c4c

Tests failed! Build no: 4404

**Comment by alfredthenarwhal** [comment]
> @adduarte:  /test install-vc7
Commit: 85afe58

Tests failed! Build no: 4440

**Comment by alfredthenarwhal** [comment]
> @adduarte:  /test install-vc7
Commit: 85afe58

Tests failed! Build no: 4443

**Comment by alfredthenarwhal** [comment]
> @adduarte:  /test install-vc7
Commit: fc33b8f

Tests passed! Build no: 4446

**Comment by adduarte** [comment]
install-vc7 test succeeded: https://gitlab.eng.vmware.com/TKG/bolt/bolt-release-yamls/-/merge_requests/4446

**Review by maralavi — APPROVED** [review]
