### PR TITLE
Fix Not Found errors in vSphere CPI/CSI Config reconciliation

### LINKED ISSUE #3223: vsphere csi/cpi config controller is not able to retrieve the correct VSphereCluster CR in non-paravirtual mode
**Bug description**
Management cluster creation for clusterclass based vsphere cluster results in package install errors for both vsphere csi and cpi:
```
E0826 21:17:19.331272       1 controller.go:317] controller/cluster "msg"="Reconciler error" "error"="failed to get remote cluster client: error creating dynamic rest mapper for remote cluster \"tkg-system/tkg-mc-vsphere\": Get \"https://10.184.90.139:6443/api?timeout=10s\": dial tcp 10.184.90.139:6443: i/o timeout" "name"="tkg-mc-vsphere" "namespace"="tkg-system" "reconciler group"="cluster.x-k8s.io" "reconciler kind"="Cluster" 
...
E0826 21:17:21.857637       1 vspherecsiconfig_controller.go:250] VSphereCSIConfig "msg"="Error while mapping VSphereCSIConfig to data values" "error"="VSphereCluster tkg-system/tkg-mc-vsphere not found" "VSphereCSIConfig"={"Namespace":"tkg-system","Name":"tkg-mc-vsphere-vsphere-csi-package"} 
...
E0826 21:45:43.630401       1 vspherecpiconfig_controller.go:171] VSphereCPIConfig "msg"="Error while mapping VSphereCPIConfig to data values" "error"="VSphereCluster tkg-system/tkg-mc-vsphere not found" "VSphereCPIConfig"={"Namespace":"tkg-system","Name":"tkg-mc-vsphere"} 
```

**Affected product area (please put an X in all that apply)**

- ( ) APIs
- (x) Addons
- ( ) CLI
- ( ) Docs
- ( ) IAM
- ( ) Installation
- ( ) Plugin
- ( ) Security
- ( ) Test and Release
- ( ) User Experience
- ( ) Developer Experience

**Expected behavior**
VSphereCluster is mapped correctly

**Steps to reproduce the bug**
Create cc based management cluster on vsphere and observe that CSI/CPI packages are not installed successfully.

**Version** (include the SHA if the version is not obvious)

**Environment where the bug was observed (cloud, OS, etc)**

**Relevant Debug Output (Logs, manifests, etc)**

### PR DESCRIPTION
**Pull request by DanielXiao**
### What this PR does / why we need it
Fetches CAPV objects through Cluster infrastructure references

A Cluster object contains a infrastructureRef and a controlPlaneRef
from which we can find the corresponding vSphereCluster and
vSphereMachineTemplate.

Refactor existing methods to match them through these references
rather than labels.

### Which issue(s) this PR fixes

Fixes #3223 

### Describe testing done for PR
Created vSphere management and workload clusters to verify change

### Release note

```release-note

```

### CODE REVIEW

**Comment by vuil** [comment]
nit: Please update the title of the PR

File: addons/controllers/cpi/vspherecpiconfig_utils.go [hunk 1]
```diff
@@ -84,27 +78,9 @@ func (r *VSphereCPIConfigReconciler) mapCPIConfigToDataValuesNonParavirtual( //
 		d.NoProxy = cluster.Annotations[pkgtypes.NoProxyConfigAnnotation]
 	}
 
-	// derive nsxt related configs from cluster variable
```
Comment (lubronzhan) [inline addons/controllers/cpi/vspherecpiconfig_utils.go:87]: Is it possible to keep this. Or remove it in a different PR, so that in the future we could revert it if we decide to consume parameters from Cluster variables

**Comment by lubronzhan** [comment]
Looks like the test needs to be fixed

File: addons/controllers/cpi/vspherecpiconfig_utils.go (hunk 1 above)
Comment (DanielXiao) [reply addons/controllers/cpi/vspherecpiconfig_utils.go:87]: I am not sure if it is safe to keep them. But they will never be Cluster variables since it is addon related configurations.

**Comment by HL-EverGreen** [comment]
+1 to Lubron's comment, looks good as long as the tests are fixed

File: addons/controllers/cpi/vspherecpiconfig_utils.go (hunk 1 above)
Comment (lubronzhan) [reply addons/controllers/cpi/vspherecpiconfig_utils.go:87]: We already designed to expose kubevipCloudProvider configuration in Cluster.spec.topology.variables. The experience would be bad if customer has to modify several CRDs to create a single Cluster

Comment (lubronzhan) [reply addons/controllers/cpi/vspherecpiconfig_utils.go:87]: Ok you can remove it then

File: addons/controllers/utils/utils.go [hunk 2]
```diff
@@ -11,28 +11,80 @@ import (
...
+	labelSelector = labelSelector.Add(*labelMatch, *labelNotMatch)
+	if err := clt.List(ctx, vSphereMachineTemplates, &client.ListOptions{LabelSelector: labelSelector, Namespace: cluster.Namespace}); err != nil {
+		return nil, err
+	}
+	if len(vSphereMachineTemplates.Items) != 1 {
+		return nil, fmt.Errorf("expected to find 1 vSphereMachineTemplate object with requirements %s in namespace %s but found %d",
+			labelSelector, cluster.Namespace, len(vSphereMachineTemplates.Items))
 	}
-	return vsphereCluster, nil
+	return &vSphereMachineTemplates.Items[0], nil
```
Comment (randomvariable) [inline addons/controllers/utils/utils.go:87]: How does this ensure you have the control plane machine template?

File: addons/controllers/utils/utils.go [hunk 3]
```diff
@@ -11,28 +11,80 @@ import (
...
+	}
+	if len(vsphereClusters.Items) != 1 {
+		return nil, fmt.Errorf("expected to find 1 VSphereCluster object for label key %s and value %s but found %d",
+			clusterapiv1beta1.ClusterLabelName, cluster.Name, len(vsphereClusters.Items))
+	}
+	return &vsphereClusters.Items[0], nil
+}
+
+// GetControlPlaneVsphereMachineTemplate gets the VsphereMachineTemplate CR of control plane
+func GetControlPlaneVsphereMachineTemplate(ctx context.Context, clt client.Client, cluster *clusterapiv1beta1.Cluster) (*capvv1beta1.VSphereMachineTemplate, error) {
```
Comment (randomvariable) [inline addons/controllers/utils/utils.go:67]: ControlPlaneVsphereMachineTemplateForCluster would be a more accurate function name (dropping Get is more conventional in k8s/capi).

File: addons/controllers/utils/utils.go [hunk 4]
```diff
@@ -11,28 +11,80 @@ import (
...
-	if err := clt.Get(ctx, types.NamespacedName{
-		Namespace: cluster.Namespace,
-		Name:      cluster.Name,
-	}, vsphereCluster); err != nil {
-		if apierrors.IsNotFound(err) {
-			return nil, errors.Errorf("VSphereCluster %s/%s not found", cluster.Namespace, cluster.Name)
-		}
-		return nil, errors.Errorf("VSphereCluster %s/%s could not be fetched, error %v", cluster.Namespace, cluster.Name, err)
+// GetVSphereClusterParavirtual gets the VSphereCluster CR for the cluster object in paravirtual mode
+func GetVSphereClusterParavirtual(ctx context.Context, clt client.Client, cluster *clusterapiv1beta1.Cluster) (*capvvmwarev1beta1.VSphereCluster, error) {
```
Comment (randomvariable) [inline addons/controllers/utils/utils.go:27]: Rename VSphereClusterParavirtualForCAPICluster (see comment below)

File: addons/controllers/utils/utils.go [hunk 5]
```diff
@@ -11,28 +11,80 @@ import (
...
+	}
+	if len(vsphereClusters.Items) != 1 {
+		return nil, fmt.Errorf("expected to find 1 VSphereCluster object for label key %s and value %s but found %d",
+			clusterapiv1beta1.ClusterLabelName, cluster.Name, len(vsphereClusters.Items))
+	}
+	return &vsphereClusters.Items[0], nil
+}
+
+// GetVSphereClusterNonParavirtual gets the VSphereCluster CR for the cluster object in non-paravirtual mode
+func GetVSphereClusterNonParavirtual(ctx context.Context, clt client.Client, cluster *clusterapiv1beta1.Cluster) (*capvv1beta1.VSphereCluster, error) {
```
Comment (randomvariable) [inline addons/controllers/utils/utils.go:47]: VSphereClusterNonParavirtualForCluster

File: addons/controllers/utils/utils.go (hunk 2 above)
Comment (randomvariable) [reply addons/controllers/utils/utils.go:87]: You really need to do something like "KubeadmControlPlaneForCluster" , then introspect that and follow the infrastructureRef

File: addons/controllers/utils/utils.go [hunk 6]
```diff
@@ -11,28 +11,80 @@ import (
...
+	labelSelector := labels.NewSelector()
+	labelSelector = labelSelector.Add(*labelMatch)
+	if err := clt.List(ctx, vsphereClusters, &client.ListOptions{LabelSelector: labelSelector, Namespace: cluster.Namespace}); err != nil {
+		return nil, err
+	}
+	if len(vsphereClusters.Items) != 1 {
+		return nil, fmt.Errorf("expected to find 1 VSphereCluster object for label key %s and value %s but found %d",
+			clusterapiv1beta1.ClusterLabelName, cluster.Name, len(vsphereClusters.Items))
+	}
+	return &vsphereClusters.Items[0], nil
```
Comment (randomvariable) [inline addons/controllers/utils/utils.go:43]: Can't we follow the infrastructureRef of the Cluster resource instead of matching on name?

File: addons/controllers/utils/utils.go (hunk 2 above)
Comment (DanielXiao) [reply addons/controllers/utils/utils.go:87]: 2 labels are used to filter out only control plane machine template:

- `cluster.x-k8s.io/cluster-name` = Cluster Name.
- `topology.cluster.x-k8s.io/deployment-name` does not exist.

Yes, infrastructureRef is more clear but increase UX complexity because users need to understand it and specify it correctly. Leave this to @lubronzhan because it 's about a design change.

File: addons/controllers/utils/utils.go (hunk 6 above)
Comment (DanielXiao) [reply addons/controllers/utils/utils.go:43]: Since this suggestion requires API and UX change, leave it to CPI team @lubronzhan .

File: addons/controllers/utils/utils.go (hunk 2 above)
Comment (DanielXiao) [reply addons/controllers/utils/utils.go:87]: Thanks, got your point. I can get it from Cluster spec.controlPlaneRef -> KubeadmControlPlane spec.machineTemplate

File: addons/controllers/utils/utils.go (hunk 6 above)
Comment (DanielXiao) [reply addons/controllers/utils/utils.go:43]: Thanks. I should get it from infrastructureRef.

File: addons/controllers/cpi/vspherecpiconfig_utils.go [hunk 7]
```diff
@@ -133,27 +127,9 @@ func (r *VSphereCPIConfigReconciler) mapCPIConfigToDataValuesNonParavirtual( //
...
-	d.Nsxt.PodRoutingEnabled = r.tryParseClusterVariableBool(cluster, NsxtPodRoutingEnabledVarName)
```
Comment (HanFa) [inline addons/controllers/cpi/vspherecpiconfig_utils.go:137]: are we no longer deriving those nsxt configs from cluster variables?

File: addons/controllers/csi/vspherecsiconfig_utils.go [hunk 8]
```diff
@@ -91,26 +90,21 @@ func (r *VSphereCSIConfigReconciler) mapVSphereCSIConfigToDataValuesNonParavirtu
...
-		return nil, errors.Errorf("VSphereMachineTemplate %s/%s could not be fetched, error %v", cluster.Namespace, cutil.ControlPlaneName(cluster.Name), err)
+	// get the control plane machine template
+	cpMachineTemplate, err := cutil.ControlPlaneVsphereMachineTemplateNonParavirtualForCluster(ctx, r.Client, cluster)
+	if err != nil {
+		return nil, err
 	}
 
 	dvs.VSphereCSI.Datacenter = cpMachineTemplate.Spec.Template.Spec.Datacenter
-	dvs.VSphereCSI.PublicNetwork = cutil.TryParseClusterVariableString(ctx, cluster, VSphereNetworkVarName)
+	dvs.VSphereCSI.PublicNetwork = cpMachineTemplate.Spec.Template.Spec.Network.Devices[0].NetworkName
```
Comment (HanFa) [inline addons/controllers/csi/vspherecsiconfig_utils.go:107]: need to check if Devices is empty, otherwise the controller might panic

File: addons/controllers/cpi/vspherecpiconfig_utils.go (hunk 7 above)
Comment (DanielXiao) [reply addons/controllers/cpi/vspherecpiconfig_utils.go:137]: Yes, they are not related to topology and will never be Cluster variables

File: addons/controllers/csi/vspherecsiconfig_utils.go (hunk 8 above)
Comment (DanielXiao) [reply addons/controllers/csi/vspherecsiconfig_utils.go]: Done.

**Review by haoranleo — APPROVED** [review]
Looks good

File: addons/controllers/cpi/vspherecpiconfig_utils.go (hunk 7 above)
Comment (HanFa) [reply addons/controllers/cpi/vspherecpiconfig_utils.go:137]: thanks. I see now. those nsxt fields for CPI package are only coming from CPIConfig resource that are set by the addon

**Review by HanFa — APPROVED** [review]
lgtm
