### PR TITLE
Handle nil secret for KappControllerConfig

### LINKED ISSUE #2727: TKG addon Controller crash loop due to nil pointer
**Bug description**
```
I0623 08:22:52.535501       1 clusterbootstrap_controller.go:178] ClusterBootstrapController "msg"="Reconciling cluster" "cluster-name"="chenrui-wc" "cluster-ns"="chenrui"
I0623 08:22:52.535759       1 clusterbootstrap_controller.go:1228] ClusterBootstrapController "msg"="setting proxy and network configurations in Cluster annotation" "cluster-name"="chenrui-wc" "cluster-ns"="chenrui" "tkg.tanzu.vmware.com/skip-tls-verify"="" "tkg.tanzu.vmware.com/tkg-http-proxy"="" "tkg.tanzu.vmware.com/tkg-https-proxy"="" "tkg.tanzu.vmware.com/tkg-ip-family"="" "tkg.tanzu.vmware.com/tkg-no-proxy"="" "tkg.tanzu.vmware.com/tkg-proxy-ca-cert"=""
I0623 08:22:52.542916       1 clusterbootstrap_controller.go:1147] ClusterBootstrapController "msg"="provider status does not have secretRef"  "GVR"={"Group":"run.tanzu.vmware.com","Version":"v1alpha3","Resource":"kappcontrollerconfigs"}
I0623 08:22:52.542937       1 clusterbootstrap_controller.go:914] ClusterBootstrapController "msg"="no data values secret is needed for ClusterBootstrapPackage: kapp-controller.tanzu.vmware.com.0.34.0+vmware.1-tkg.1-zshippable, nothing to be created or patched on cluster chenrui/chenrui-wc"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1665999]

goroutine 1700 [running]:
github.com/vmware-tanzu/tanzu-framework/addons/controllers.(*ClusterBootstrapReconciler).createOrPatchKappPackageInstall.func1()
	/workspace/addons/controllers/clusterbootstrap_controller.go:622 +0x2d9
sigs.k8s.io/controller-runtime/pkg/controller/controllerutil.mutate(0x1d06bc0, {{0xc000ba1050, 0xc0003d05c0}, {0xc0013395c0, 0xc001b078c8}}, {0x1d88a78, 0xc0015da960})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/controller/controllerutil/controllerutil.go:339 +0x4f
sigs.k8s.io/controller-runtime/pkg/controller/controllerutil.CreateOrPatch({0x1d38910, 0xc0003d05c0}, {0x1d69d78, 0xc00007f310}, {0x1d88a78, 0xc0015da960}, 0xc001b07a48)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/controller/controllerutil/controllerutil.go:239 +0x134
github.com/vmware-tanzu/tanzu-framework/addons/controllers.(*ClusterBootstrapReconciler).createOrPatchKappPackageInstall(0xc0001b1400, 0xc0009ca420, 0xc000fae000)
	/workspace/addons/controllers/clusterbootstrap_controller.go:629 +0x5e5
github.com/vmware-tanzu/tanzu-framework/addons/controllers.(*ClusterBootstrapReconciler).reconcileNormal(0xc0001b1400, 0xc000fae000, {{0x1d56680, 0xc001a9e910}, 0x13})
	/workspace/addons/controllers/clusterbootstrap_controller.go:211 +0x1f6
github.com/vmware-tanzu/tanzu-framework/addons/controllers.(*ClusterBootstrapReconciler).Reconcile(0xc0001b1400, {0x1d389b8, 0xc001ae5ce0}, {{{0xc000ba1050, 0x19fcce0}, {0xc000ba1040, 0x30}}})
	/workspace/addons/controllers/clusterbootstrap_controller.go:184 +0x4b9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc0000d86e0, {0x1d389b8, 0xc001ae5cb0}, {{{0xc000ba1050, 0x19fcce0}, {0xc000ba1040, 0x413bf4}}})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:114 +0x26f
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0000d86e0, {0x1d38910, 0xc000508ec0}, {0x1918e60, 0xc0012caa60})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:311 +0x33e
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0000d86e0, {0x1d38910, 0xc000508ec0})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:266 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:227 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:223 +0x357
```

This error is because ClusterBootstrap Controller expect the referenced kapp provider KappControllerConfig returns a secret that stored its status. This secret will be added to the pkgi secretRef for kapp package install.
https://github.com/vmware-tanzu/tanzu-framework/blob/c4a3917d081a9933aab865c0c5632ed03118c069/addons/controllers/clusterbootstrap_controller.go#L617-L625

But the kapp provider KappControllerConfig's secret in the status is generated by the KappControllerConfig Controller, and during the reconciliation this secret status may not be updated yet.
https://github.com/vmware-tanzu/tanzu-framework/blob/c4a3917d081a9933aab865c0c5632ed03118c069/addons/controllers/kapp-controller/kappcontrollerconfig_controller.go#L159-L160

So the ClusterBootstrap Controller will receive an empty secret, and no errors returned.
https://github.com/vmware-tanzu/tanzu-framework/blob/c4a3917d081a9933aab865c0c5632ed03118c069/addons/controllers/clusterbootstrap_controller.go#L909-L918

Then when ClusterBootstrap updating the kapp pkgi secretRef , it is using a secret name which the secret itself is a nil pointer.

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [x] Addons
- [ ] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Expected behavior**
No such error

**Steps to reproduce the bug**
Manually create the utkg workload cluster by applying customized ClusterBootstrap and KappControllerConfig.

**Version** (include the SHA if the version is not obvious)
TKG

**Environment where the bug was observed (cloud, OS, etc)**
TKG aws

### PR DESCRIPTION
**Pull request by vijaykatam**
A controller race can cause crash of clusterbootstrap_controller
when controller for kapp config has not finished reconciling

Signed-off-by: Vijay Katam <vkatam@vmware.com>

### What this PR does / why we need it

A controller race can cause crash of clusterbootstrap_controller
when controller for kapp config has not finished reconciling

### Which issue(s) this PR fixes

Fixes #2727 

### Describe testing done for PR

Integration test via env test

### Release note

```release-note
package-based-lcm: fix crash in clusterbootstrap_controller due to nil secret
```

### PR Checklist

- [x] Squash the commits into one or a small number of logical commits
      
- [x] Use good commit [messages](https://github.com/vmware-tanzu/tanzu-framework/blob/main/CONTRIBUTING.md)
- [x] Ensure PR contains terms all contributors can understand and links all contributors can access

### CODE REVIEW

**Review by maralavi — APPROVED** [review]

**Comment by maralavi** [comment]
That's true, its quite possible that kapp controller config controller has not finished adding the secret yet while clusterbootstrap controller is trying to fetch the secret... Thanks for the PR!

File: addons/controllers/clusterbootstrap_controller_test.go [hunk 1]
```diff
@@ -994,6 +994,41 @@ var _ = Describe("ClusterBootstrap Reconciler", func() {
...
+					Name: clusterNamespace,
+				},
+			}
+			err := k8sClient.Create(ctx, ns)
+			if err != nil {
+				Expect(apierrors.IsAlreadyExists(err)).To(BeTrue())
+			}
+		})
+		Context("controller should not crash", func() {
+			It("and create pacakge install for kapp ", func() {
```
Comment (maralavi) [inline addons/controllers/clusterbootstrap_controller_test.go:1014]: ```pacakge``` --> ```package```

File: addons/controllers/clusterbootstrap_controller.go [hunk 2]
```diff
@@ -626,10 +626,16 @@ func (r *ClusterBootstrapReconciler) createOrPatchKappPackageInstall(clusterBoot
...
-				Name: secret.Name},
-			},
+		if secret != nil {
+			pkgi.Spec.Values = []kapppkgiv1alpha1.PackageInstallValues{
+				{SecretRef: &kapppkgiv1alpha1.PackageInstallValuesSecretRef{
+					Name: secret.Name},
+				},
+			}
+		} else {
+			r.Log.Info("[Warning]: Empty secret for kapp-controller package. Either kappcontrollerconfig_controller has not reconciled yet or "+
```
Comment (maralavi) [inline addons/controllers/clusterbootstrap_controller.go:636]: nit: ```kappcontrollerconfig_controller``` -> ```KappControllerConfig controller```
