### PR TITLE
fix #3817  use latest available k8s version if not specified when upgrading cluster

### LINKED ISSUE #3817: tanzu upgrade command returns "no upgrade available" after failing verification in a prior invocation
**Bug description**
1. When trying to upgrade (without arguments), we shouldn't default to the highest version; we should default to the highest valid version. If you're on v1.X, we shouldn't try to upgrade to v1.(X+2)

2. When an upgrade fails because we've attempted to skip a minor version, it seems like we need a better way to recover; just retrying with the right version should work.

**Affected product area (please put an X in all that apply)**

- ( ) APIs
- ( ) Addons
- (x ) CLI
- ( ) Docs
- ( ) IAM
- ( ) Installation
- ( ) Plugin
- ( ) Security
- ( ) Test and Release
- ( ) User Experience
- ( ) Developer Experience

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the SHA if the version is not obvious)

**Environment where the bug was observed (cloud, OS, etc)**

**Relevant Debug Output (Logs, manifests, etc)**
- should handle empty tkrversion/k8s version correct instead of using default k8s version: https://github.com/vmware-tanzu/tanzu-framework/blob/main/tkg/tkgctl/upgrade_cluster.go#L64 
- should restore tkr version label if upgrade failed https://github.com/vmware-tanzu/tanzu-framework/blob/main/tkg/client/upgrade_cluster.go#L181

### PR DESCRIPTION
**Pull request by hongtaiwang**
### What this PR does / why we need it

* restore to previous k8s version if upgrade failed for cc clusters

* restore to previous tkr version label if upgrade failed for legacy clusters

* use latest available k8s version if not specified when upgrading cluster
### Which issue(s) this PR fixes

Fixes #3817 

### Describe testing done for PR

tests done on local testbed:
* restore tkr label for clusters when upgrade failing
```
Upgrading workload cluster 'my-legacy-wc' to kubernetes version 'v1.23.13+vmware.1'. Are you sure? [y/N]: y
Warning: Use of ytt based cluster templates will be deprecated in favor of ClusterClass templates in a future version of TKG. Please work to move your workloads to a ClusterClass enabled cluster.
Verifying kubernetes version...
Upgrading kubernetes cluster from `v1.22.11---vmware.2-tkg.2-zshippable` to `v1.23.13+vmware.1-tkg.1-zshippable` version
Restoring kubernetes cluster to tkr `v1.22.11---vmware.2-tkg.2-zshippable` version
```
* restore k8s version for cc cluster when upgrade failing
```
Upgrading workload cluster 'my-wc1' to kubernetes version 'v1.24.6+vmware.1'. Are you sure? [y/N]: y
Upgrading kubernetes cluster from `v1.22.11+vmware.2` to `v1.24.6+vmware.1` version
Restoring kubernetes cluster to `v1.22.11+vmware.2` version
```

* use latest available version when upgrade cluster without `--tkr` specified
```
kubo@0LZ8DZiMkuKTi:~/tanzu-framework$ tanzu cluster upgrade my-legacy-wc
Upgrading workload cluster 'my-legacy-wc' to kubernetes version 'v1.23.13+vmware.1'. Are you sure? [y/N]: y
Warning: Use of ytt based cluster templates will be deprecated in favor of ClusterClass templates in a future version of TKG. Please work to move your workloads to a ClusterClass enabled cluster.
Verifying kubernetes version...
Upgrading kubernetes cluster from `v1.22.11---vmware.2-tkg.2-zshippable` to `v1.23.13+vmware.1-tkg.1-zshippable` version
Retrieving configuration for upgrade cluster...
Create InfrastructureTemplate for upgrade...
Upgrading control plane nodes...
Patching KubeadmControlPlane with the kubernetes version v1.23.13+vmware.1...
Updating the KCP object with k8s version v1.23.13+vmware.1
Waiting for kubernetes version to be updated for control plane nodes
Upgrading worker nodes...
Patching MachineDeployment with the kubernetes version v1.23.13+vmware.1...
Waiting for kubernetes version to be updated for worker nodes...
Waiting for packages to be up and running...
Cluster 'my-legacy-wc' successfully upgraded to kubernetes version 'v1.23.13+vmware.1'
```

### Release note

```release-note

```

### CODE REVIEW

File: tkg/client/upgrade_cluster.go [hunk 1]
```diff
@@ -181,18 +181,35 @@ func (c *TkgClient) UpgradeCluster(options *UpgradeClusterOptions) error {
...
 	if err != nil {
 		return errors.Wrapf(err, "unable to patch the cluster object with TanzuKubernetesRelease label")
 	}
 
+	// restore tkr version if upgrade failed after tkr label updated
+	defer func() {
+		if err != nil {
+			log.Infof("Restoring kubernetes cluster to tkr `%v` version", currentTkrVersion)
+			options.TkrVersion = currentTkrVersion
+			if restoreErr := c.addKubernetesReleaseLabel(regionalClusterClient, options); restoreErr != nil {
```
Comment (12345lcr) [inline tkg/client/upgrade_cluster.go:207]: Hi @hongtaiwang , what if the cluster node is successfully upgraded and all the core addons are upgraded, but one of the addon's reconciliation just got a little timeout? I think switching the tkr version back to origin no matter what the error is will result in some unexpected behavior, like the successfully reconciled core addons will be downgraded , which is either not allowed by kapp or bring compatibility issues.

Comment (hongtaiwang) [reply tkg/client/upgrade_cluster.go:207]: does kapp refer to  `tanzuKubernetesRelease` label for legacy cluster or `topology.version` for cc cluster? 

The revert is only for those fields when upgrade failed. If upgrade failed due to some reason, it's expected that the cluster is broken, and users should be able to re-run the upgrade command to get through it.

File: tkg/client/upgrade_cluster.go [hunk 2]
```diff
@@ -181,18 +181,35 @@ func (c *TkgClient) UpgradeCluster(options *UpgradeClusterOptions) error {
...
 	err = c.addKubernetesReleaseLabel(regionalClusterClient, options)
 	if err != nil {
 		return errors.Wrapf(err, "unable to patch the cluster object with TanzuKubernetesRelease label")
 	}
 
+	// restore tkr version if upgrade failed after tkr label updated
+	defer func() {
+		if err != nil {
+			log.Infof("Restoring kubernetes cluster to tkr `%v` version", currentTkrVersion)
+			options.TkrVersion = currentTkrVersion
```
Comment (jeffwubj) [inline tkg/client/upgrade_cluster.go:206]: besides @12345lcr 's comments, curious what will be the suggested actions for users after setting tkr version back to the original version? upgrade again directly or do some "repair" then upgrade? if user need to do some manual "repair", seems set tkr version back could be part of that as well

Comment (hongtaiwang) [reply tkg/client/upgrade_cluster.go:206]: > upgrade again directly or do some "repair" then upgrade?
either way should be good, depends on what kind of error they meet. But if the version is not set back, customer will not be able to run upgrade again since the current version is overwritten and tanzu cli does not support upgrade to "old" versions.

File: tkg/client/upgrade_cluster.go (hunk 1 above)
Comment (12345lcr) [reply tkg/client/upgrade_cluster.go:207]: `tanzuKubernetesRelease` took effect on tanzu cli, addons-manager, pinniped... I am not sure what is the full consequence for these components to set it back and forth.

And also `tanzuKubernetesRelease` is a legacy tkr label. In ClusterClass clusters the tkr label seems to be `run.tanzu.vmware.com/tkr`.

Comment (hongtaiwang) [reply tkg/client/upgrade_cluster.go:207]: tanzu cli upgrade cluster read `tanzuKubernetesRelease` in legacy clusters , while `topology.version`  in cc clusters.

Comment (12345lcr) [reply tkg/client/upgrade_cluster.go:207]: From the addon-manager's perspective, this `tanzuKubernetesRelease` decide which core package repository should be deployed to to legacy wl cluster. Once it is updated the core addon's upgrade is started.

Comment (12345lcr) [reply tkg/client/upgrade_cluster.go:207]: So what I mean is this `tanzuKubernetesRelease` is a very high level information that multiple components are depends on it. If the cluster upgrade is failed and we want to retry, it is better to have something like a `force upgrade` to adjust the cluster into the desired state, instead of `fake` the cluster that the upgrade did not happened before.

Comment (12345lcr) [reply tkg/client/upgrade_cluster.go:207]: And maybe the better solution is to block the upgrade from beginning if it tries to skip a minor version

Comment (hongtaiwang) [reply tkg/client/upgrade_cluster.go:207]: But I still think upgrade tag should be the last step for upgrade cluster since we should not set the cluster to new version if the upgrade process is not finished completely. 

And of course the impact for addon-manager should be taken into consideration. Do you know if addon-manager could work after the following update?
* set tkr v1 -> v2 during upgrade
* upgrade fail after addon-manager updated, set back v2 -> v1 (maybe addon-manager will be broken now)
* re-run upgrade command, v1 -> v2 again ===> could addon-manager work correctly in this case?

Comment (12345lcr) [reply tkg/client/upgrade_cluster.go:207]: > upgrade tag should be the last step for upgrade cluster 

This was the previous behavior that brought problems. The core addon's upgrade path is `upgrade tkr tag in cluster-> addons manager upgrade core addon's repo -> kapp-controller upgrade core addon`

In this path if the tkr is updated at the final step, then this means the core addons got updated after node upgrade, but if the old addons were not compatible with new version kubernetes nodes, the upgrade will hang on
* Node upgrade stuck because nodes not ready, due to old core addons not compatible
* Addons cannot be upgraded because nodes upgrade was not finished successfully

File: tkg/client/upgrade_cluster.go [hunk 3]
```diff
@@ -181,18 +181,35 @@
 	return c.DoLegacyClusterUpgrade(regionalClusterClient, currentClusterClient, options)
 }
 
-func (c *TkgClient) DoLegacyClusterUpgrade(regionalClusterClient, currentClusterClient clusterclient.Client, options *UpgradeClusterOptions) error {
+func (c *TkgClient) DoLegacyClusterUpgrade(regionalClusterClient, currentClusterClient clusterclient.Client, options *UpgradeClusterOptions) (err error) {
```
Comment (imikushin) [inline tkg/client/upgrade_cluster.go:184]: **suggestion:** rename `err` to `retErr` to avoid accidental assignment to the return variable in the method body. It's best to _only_ access `retErr` in the _deferred_ func.

In the method body, write return statements as usual (_do not_ assign to `retErr`).

File: tkg/client/upgrade_cluster.go [hunk 4]
```diff
@@ -181,18 +181,35 @@
...
 	log.Info("Verifying kubernetes version...")
-	err := c.verifyK8sVersion(currentClusterClient, options.KubernetesVersion)
+	err = c.verifyK8sVersion(currentClusterClient, options.KubernetesVersion)
 	if err != nil {
 		return errors.Wrap(err, "kubernetes version verification failed")
 	}
 
+	// backup tkr version for current cluster
+	currentClusterInfo := regionalClusterClient.GetClusterStatusInfo(options.ClusterName, options.Namespace, currentClusterClient)
+	currentTkrVersion := currentClusterInfo.ClusterObject.Labels["tanzuKubernetesRelease"]
```
Comment (imikushin) [inline tkg/client/upgrade_cluster.go:193]: **nit:** Since `currentClusterInfo` only exists to help obtain `currentTkrVersion`, perhaps it would be helpful to introduce a function that would return `currentTkrVersion`. 

Also, I believe we have a constant for `"tanzuKubernetesRelease"`. If it's not convenient to import it here, it's still better to use a constant rather than a string value.

File: cmd/cli/plugin/cluster/upgrade.go [hunk 5]
```diff
@@ -364,6 +361,11 @@
 		return "", errors.Errorf("no available upgrades for cluster '%s', namespace '%s'", cluster.Name, cluster.Namespace)
 	}
 
+	// if tkrname is not specified, return the latest available version
+	if tkrName == "" {
+		return latestTkrVersion(updates.Slice()), nil
+	}
```
[the remark this answers is not in the document]
Comment (hongtaiwang) [reply cmd/cli/plugin/cluster/upgrade.go]: addressed

File: tkg/client/upgrade_cluster.go (hunk 3 above)
Comment (hongtaiwang) [reply tkg/client/upgrade_cluster.go]: done

File: tkg/client/upgrade_cluster.go (hunk 4 above)
Comment (hongtaiwang) [reply tkg/client/upgrade_cluster.go]: done

**Comment by hongtaiwang** [comment]
As discussed, we are not going to restore k8s/tkr version when upgrade failed.

**Review by jeffwubj — APPROVED** [review]

File: cmd/cli/plugin/cluster/upgrade.go [hunk 6]
```diff
@@ -115,18 +115,15 @@ func upgradeCluster(server *configapi.Server, clusterName string) error {
 		return err
 	}
 
-	tkrVersion := ""
-	if uc.tkrName != "" {
```
Comment (wjun) [inline cmd/cli/plugin/cluster/upgrade.go:119]: Why do we remove this condition here?

File: cmd/cli/plugin/cluster/upgrade.go [hunk 7]
```diff
@@ -352,6 +349,15 @@ func getClusterTKRNameFromClusterLabels(clusterLabels map[string]string) (string
 }
 
 func getValidTKRVersionFromClusterForUpgrade(cluster *capiv1.Cluster, tkrName string) (string, error) {
+	// if tkrname is not specified, return the latest available version
```
Comment (wjun) [inline cmd/cli/plugin/cluster/upgrade.go:352]: From the issue description, we should avoid upgrade from 1.22 to 1.24. How is this latest available version satisfy this condition?

Comment (hongtaiwang) [reply cmd/cli/plugin/cluster/upgrade.go:352]: this label is tagged by tkr-status-controller https://github.com/vmware-tanzu/tanzu-framework/blob/6c7f5cc18a6caeed6724e88ebbe90ccd05e35e7f/tkr/controller/tkr-status/clusterstatus/clusterstatus.go#L183 . It is selected from tkrs within minor+1 version.

File: cmd/cli/plugin/cluster/upgrade.go (hunk 6 above)
Comment (hongtaiwang) [reply cmd/cli/plugin/cluster/upgrade.go:119]: because `getValidTkrVersionFromTkrForUpgrade` should return highest available tkr if `tkrName` is not specified. And it should be called if `tkrName` is empty.

**Review by wjun — APPROVED** [review]
LGTM
