### PR TITLE
Fix the issue where upgrade operation fails for vSphere cluster if vSphere password contains single quote(')

### LINKED ISSUE #1721: Management cluster upgrade fails if vSphere password contains a single quote
**Bug description**
Upgrade operation failed with below error when vSphere password contains a single quote

```
cluster specific secret is not present, fallback on bootstrap credential secret
Error: unable to configure variables for provider installation: failed to configure Vsphere credentials: unable to get vsphere credentials from secret: unable to retrieve vSphere credentials: yaml: line 1: did not find expected key
```

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [ ] Addons
- [x] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Expected behavior**
Upgrade should be successful.
Since the `capv-manager-bootstrap-credentials` secret is an artifact from upstream(capv-provider), the logic should atleast try to read the credentials from cluster's identityRef secret before falling back to reading credentials from `capv-manager-bootstrap-credentials` secret.
**Steps to reproduce the bug**

**Version** (include the SHA if the version is not obvious)
1.4.1
**Environment where the bug was observed (cloud, OS, etc)**

**Relevant Debug Output (Logs, manifests, etc)**

### PR DESCRIPTION
**Pull request by prkalle**
### What this PR does / why we need it
This PR fixes upgrade operation failing due to the unmarshaling error while trying to read the vSphere credentials from capv-manager-bootstrap-credentials secret if the vSphere password has single quotes.

The fix addresses the issue by 

- reading the credentials from cluster's(identityRef) secret(reading password from secret doesn't involve unmarshaling) before falling back to capv-manager-bootstrap-credentials secret. This fix should be good for majority of the cases, however there is a scenario(very unlikely) it would not address, where vSphere management cluster was created before cluster's secret was used.

Since `capv-manager-bootstrap-credentials` secret is an artifact from upstream, [vSphere provider Issue](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1460) is filed on upstream to support the vsphere password with single quotes and doesn't cause issue in unmarshaling. 

- use namespace along with cluster name while retreiving the credentials which would adddress the issue where the same secret name (created with cluster name) exists in different namespaces

### Which issue(s) this PR fixes

Fixes #1721 

### Describe testing done for PR

Created management cluster successfully
```
<snap>...
You can now access the management cluster test-vc-pwdfix-sai-mc by running 'kubectl config use-context test-vc-pwdfix-sai-mc-admin@test-vc-pwdfix-sai-mc'
Deleting kind cluster: tkg-kind-c8gmtabqk3vfe03s5550

Management cluster created!

You can now create your first workload cluster by running the following:

  tanzu cluster create [name] -f [file]

  kubectl get apps -A

Checking for required plugins...
Installing plugin 'cluster:v0.18.0-dev'
Installing plugin 'feature:v0.18.0-dev'
Installing plugin 'kubernetes-release:v0.18.0-dev'
Installing plugin 'login:v0.18.0-dev'
Successfully installed all required plugins
pkalle-a01:mirrors_github_tanzu-framework pkalle$

```

Upgrade the management cluster to the same version
```
Management cluster 'test-vc-pwdfix-sai-mc' successfully upgraded to TKG version 'v1.6.0-zshippable' with kubernetes version 'v1.22.5+vmware.1'
Checking for required plugins...
All required plugins are already installed and up-to-date
```

Created workload cluster on a different vsphere(multi-tenancy) and it was successful
```
$ tanzu cluster create test-pwdfix-sai-wc -f /Users/pkalle/.config/tanzu/tkg/clusterconfigs/multi_tenancy_vsphere.yaml -v 6 --tkr v1.21.8---vmware.1-tkg.3-zshippable
compatibility file (/Users/pkalle/.config/tanzu/tkg/compatibility/tkg-compatibility.yaml) already exists, skipping download
BOM files inside /Users/pkalle/.config/tanzu/tkg/bom already exists, skipping download
Using namespace from config:
Validating configuration...
……
Successfully reconciled package: metrics-server

Workload cluster 'test-pwdfix-sai-wc' created

```

Upgraded the workload cluster created on different VC and it was successful
```
$ tanzu cluster upgrade test-pwdfix-sai-wc -v6
compatibility file (/Users/pkalle/.config/tanzu/tkg/compatibility/tkg-compatibility.yaml) already exists, skipping download
BOM files inside /Users/pkalle/.config/tanzu/tkg/bom already exists, skipping download
Upgrading workload cluster 'test-pwdfix-sai-wc' to kubernetes version 'v1.22.5+vmware.1'. Are you sure? [y/N]: y
Creating management cluster client...

….

Successfully reconciled package: secretgen-controller
Successfully reconciled package: vsphere-csi
Successfully reconciled package: vsphere-cpi
Successfully reconciled package: antrea
Successfully reconciled package: metrics-server
Cluster 'test-pwdfix-sai-wc' successfully upgraded to kubernetes version 'v1.22.5+vmware.1'
```

Deleted the above workload cluster and it was successful
```
$ tanzu cluster delete test-pwdfix-sai-wc
Deleting workload cluster 'test-pwdfix-sai-wc'. Are you sure? [y/N]: y
Workload cluster 'test-pwdfix-sai-wc' is being deleted

```

Deleted the managment cluster and it was successful
```
Deleting management cluster...
Management cluster 'test-vc-pwdfix-sai-mc' deleted.
Deleting the management cluster context from the kubeconfig file '/Users/pkalle/.kube/config'
warning: this removed your active context, use "kubectl config use-context" to select a different one

Management cluster deleted!
```

### Release note

```release-note
 Fix the issue where upgrade operation fails for vSphere provider if vSphere password contains single quote(')
```

### PR Checklist

- [ ] Squash the commits into one or a small number of logical commits
      
- [ ] Use good commit [messages](https://github.com/vmware-tanzu/tanzu-framework/blob/main/CONTRIBUTING.md)
- [ ] Ensure PR contains terms all contributors can understand and links all contributors can access

#### Special notes for your reviewer

There is an upstream(vSphere provider) [ issue](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1460) filed to provide a means to support VC password which has single quote('). If there is any fix/change in the upstream, we should update the logic to read the capv-manager-bootstrap-credentials secret.

### CODE REVIEW

**Comment by vuil** [comment]
infra-components is derived from upstream. Please file an issue in CAPV to get confirmation that the proposed fix makes sense.

**Comment by prkalle** [comment]
> infra-components is derived from upstream. Please file an issue in CAPV to get confirmation that the proposed fix makes sense.

 Filed an issue upstream for the same to get suggestions/reviews for this issue:
https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1460
Also further testing, found this fix have issue if the password starts with `%` or single quote `'`.

**Review by saimanoj01 — APPROVED** [review]
LGTM

File: pkg/v1/tkg/clusterclient/credentials.go [hunk 1]
```diff
@@ -36,6 +37,28 @@ const (
 	CapvNamespace                    = "capv-system"
 )
 
+func (c *client) GetVCCredentialsFromCluster(clusterName, clusterNamespace string) (string, string, error) {
+
+	// multi-tenancy feature is introduced in TKG 1.4. credentials are saved as a cluster specific secret on the management cluster
```
Comment (vuil) [inline pkg/v1/tkg/clusterclient/credentials.go:42]: nit: some comment fix suggestions: cluster-specific, identifyRef, // TODO:,

Comment (prkalle) [reply pkg/v1/tkg/clusterclient/credentials.go]: updated
