### PR TITLE
Fix upgrade issue when latest TKR is passed on already upgrade cluster

### LINKED ISSUE #1852: Upgrade workload cluster fails, CLI reports: no available upgrades when using latest TKR
**Bug description**

When cluster is on latest TKR and user tried to run the upgrade command again with the same latest TKR, CLI throws error.
```
$ tanzu cluster upgrade wcv1218-dev -v 9 -y  --namespace=wcv1218-dev --tkr=v1.22.5---vmware.1-tkg.3 --vsphere-vm-template-name=photon-3-kube-v1.22.5+vmware.1
compatibility file (/root/.config/tanzu/tkg/compatibility/tkg-compatibility.yaml) already exists, skipping download
BOM files inside /root/.config/tanzu/tkg/bom already exists, skipping download
Error: no available upgrades for cluster "wcv1218-dev", namespace "wcv1218-dev"
```

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [ ] Addons
- [x] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Expected behavior**
Upgrade to be performed normally without throwing error.

**Steps to reproduce the bug**

**Version** (include the SHA if the version is not obvious)

**Environment where the bug was observed (cloud, OS, etc)**

**Relevant Debug Output (Logs, manifests, etc)**

### PR DESCRIPTION
**Pull request by anujc25**
### What this PR does / why we need it
- Fixes the workload cluster upgrade issue when cluster is already on
  latest TKR and user passes the same TKR with `--tkr` flag with `tanzu
  cluster upgrade` command.

### Which issue(s) this PR fixes

Fixes #1852

### Describe testing done for PR
- Manual testing by using latest TKR and running the upgrade command before and after the fix
- Added unit test for the same as well

### Release note

```release-note
Fixed the workload cluster upgrade issue when cluster is already on latest TKR and user passes the same TKR with `--tkr` flag with `tanzu  cluster upgrade` command
```

### PR Checklist

- [x] Squash the commits into one or a small number of logical commits
      
- [x] Use good commit [messages](https://github.com/vmware-tanzu/tanzu-framework/blob/main/CONTRIBUTING.md)
- [x] Ensure PR contains terms all contributors can understand and links all contributors can access

### CODE REVIEW

File: cmd/cli/plugin/cluster/upgrade.go [hunk 1]
```diff
@@ -181,6 +181,12 @@ func getValidTKRVersionForUpgradeGivenFullTKRName(clusterName, namespace string,
 		return tkrForUpgrade.Spec.Version, nil
 	}
 
+	// // If existing TKR on the cluster and the one requested are same
+	// // continue the upgrade using the given TKR
+	if tkrName == tkrForUpgrade.GetName() {
+		return tkrForUpgrade.Spec.Version, nil
+	}
+
```
Comment (imikushin) [inline cmd/cli/plugin/cluster/upgrade.go:189]: This LGTM. The only problem (nitpick, really) I have with this is this function is already too long, and is just getting longer, definitely more complex and more difficult to understand.

**Review by imikushin — APPROVED** [review]
