### PR TITLE
Fix flaky package plugin tests

### LINKED ISSUE #3324: Flaky package plugin integration tests
**Bug description**
- The package plugin integration tests fails intermittently:
```
Summarizing 1 Failure:


[Fail] Package plugin integration test testing package plugin on management cluster [It] should pass all checks on management cluster 

/home/kubo/tanzu-framework/pkg/v1/tkg/test/tkgpackageclient/package_plugin_integration_test.go:579


Ran 2 of 2 Specs in 331.886 seconds

FAIL! -- 1 Passed | 1 Failed | 0 Pending | 0 Skipped

--- FAIL: TestTkgpackageclient (331.89s)

FAIL
```

**Affected product area (please put an X in all that apply)**

- ( ) APIs
- (x) Addons
- ( ) CLI
- ( ) Docs
- ( ) IAM
- ( ) Installation
- ( ) Plugin
- ( ) Security
- ( ) Test and Release
- ( ) User Experience
- ( ) Developer Experience

**Expected behavior**
- Tests should not be flaky

**Steps to reproduce the bug**

**Version** (include the SHA if the version is not obvious)

**Environment where the bug was observed (cloud, OS, etc)**

**Relevant Debug Output (Logs, manifests, etc)**

### PR DESCRIPTION
**Pull request by haoranleo**
### What this PR does / why we need it
- Fix flaky package plugin tests by waiting for packaging API to become available after registry pod is running
- This change simply reorders the checking block in package plugin tests

-----

**Root cause of flaky plugin tests:** 

- With original checking order (first wait for packaging API become available and then wait for registry pod to be running), it might be possible that the packaging API is still available because of old `kapp-controller` pod has NOT been deleted yet.
- In this case, the checking about packaging API might pass before the `kapp-controller` actually restarts (the time old `kapp-controller` pod is replaced by new one). Which means the "make sure package API is available after kapp-controller restart" block in `setUpPrivateRegistry` function can not guarantee that the packaging API is available **AFTER** `kapp-controller` restarts
- So there might be a chance that the when the tests go into `testHelper` and tries to call package repository API, the `kapp-controller` is still in progress of restarting. As a result, packaging API is not available and thus throw error:
```
Error: failed to check for the availability of 'packaging.carvel.dev' API: failed to discover unmatched GroupVersionResources: the server is currently unable to handle the request
```

**Evidence of this analysis:**

In a pipeline run, the following logs are observed:
```
01:12:58  $ tanzu package repository list --all-namespaces --namespace test-ns --output json --kubeconfig /home/kubo/.kube/config 
01:12:58  [
01:12:58    {
01:12:58      "details": "",
01:12:58      "name": "tanzu-standard",
01:12:58      "namespace": "tanzu-package-repo-global",
01:12:58      "repository": "projects.registry.vmware.com/tkg/packages/standard/repo",
01:12:58      "status": "Reconcile succeeded",
01:12:58      "tag": "v1.6.0"
01:12:58    },
01:12:58    {
01:12:58      "details": "",
01:12:58      "name": "tanzu-core",
01:12:58      "namespace": "tkg-system",
01:12:58      "repository": "projects.registry.vmware.com/tkg/packages/core/repo",
01:12:58      "status": "Reconcile succeeded",
01:12:58      "tag": "v1.23.8_vmware.2-tkg.1"
01:12:58    }
01:12:58  ]
01:13:16  $ tanzu package repository update carvel-test --url registry-svc.registry.svc.cluster.local:443/secret-test/test-repo@sha256:e07483e2140fa427d9875aee9055d72efc49a732f3a3fb2c9651d9f39159315a --namespace test-ns --create-namespace --create --wait=true --poll-interval 20s --poll-timeout 30s --kubeconfig /home/kubo/.kube/config 
01:13:16  Error: failed to check for the availability of 'packaging.carvel.dev' API: failed to discover unmatched GroupVersionResources: the server is currently unable to handle the request
```
Note that the first `tanzu package repository list` is executed by the "make sure package API is available after kapp-controller restart" block. Which means that the packaging API is available in that check and thus the check passes. However, when the tests proceed, the packaging API becomes unavailable which fails the operations on package repository. This symptoms demonstrates that the `kapp-controller` has not finished the restart yet while the corresponding check ("make sure package API ... restart") passes.

**Reasoning for the fix:**

After switching order, the tests won't check the availability of packaging API right after deleting old `kapp-controller` pod. Instead it will first wait for registry pod to be up. So it gives time for `kapp-controller` pods to be deleted before checking, which avoids the fact that the packaging API is available is because of old `kapp-controller` pods are still running. Testing details can be seen at the `Testing done` section.

### Which issue(s) this PR fixes

Fixes #3324 

### Describe testing done for PR
Ran the pipeline multiple times and verified all of package plugin tests passed. Also observe the following log snippet which demonstrates that the "make sure package API is available after kapp-controller restart" test block is actually waiting for packaging API to become available after restart now:
```
15:56:29  $ tanzu package repository list --all-namespaces --namespace test-ns --output json --kubeconfig /home/kubo/.kube/config 
15:56:29  Error: failed to check for the availability of 'packaging.carvel.dev' API: failed to discover unmatched GroupVersionResources: the server is currently unable to handle the request
15:56:29  
15:56:29  ✖  exit status 1 
15:56:29  Error: exit status 1
15:56:29  <nil>
15:56:29  <nil>
15:56:47  $ tanzu package repository list --all-namespaces --namespace test-ns --output json --kubeconfig /home/kubo/.kube/config 
15:56:47  Error: failed to check for the availability of 'packaging.carvel.dev' API: failed to discover unmatched GroupVersionResources: the server is currently unable to handle the request
15:56:47  
15:56:47  ✖  exit status 1 
15:56:47  Error: exit status 1
15:56:47  <nil>
15:56:47  <nil>
15:57:02  $ tanzu package repository list --all-namespaces --namespace test-ns --output json --kubeconfig /home/kubo/.kube/config 
15:57:02  Error: failed to check for the availability of 'packaging.carvel.dev' API: failed to discover unmatched GroupVersionResources: the server is currently unable to handle the request
15:57:02  
15:57:02  ✖  exit status 1 
15:57:02  Error: exit status 1
15:57:02  <nil>
15:57:02  <nil>
15:57:20  $ tanzu package repository list --all-namespaces --namespace test-ns --output json --kubeconfig /home/kubo/.kube/config 
15:57:20  Error: failed to check for the availability of 'packaging.carvel.dev' API: failed to discover unmatched GroupVersionResources: the server is currently unable to handle the request
15:57:20  
15:57:20  ✖  exit status 1 
15:57:20  Error: exit status 1
15:57:20  <nil>
15:57:20  <nil>
15:57:35  $ tanzu package repository list --all-namespaces --namespace test-ns --output json --kubeconfig /home/kubo/.kube/config 
15:57:35  [
15:57:35    {
15:57:35      "details": "",
15:57:35      "name": "tanzu-standard",
15:57:35      "namespace": "tanzu-package-repo-global",
15:57:35      "repository": "projects.registry.vmware.com/tkg/packages/standard/repo",
15:57:35      "status": "Reconcile succeeded",
15:57:35      "tag": "v1.6.0"
15:57:35    },
15:57:35    {
15:57:35      "details": "",
15:57:35      "name": "tanzu-core",
15:57:35      "namespace": "tkg-system",
15:57:35      "repository": "projects.registry.vmware.com/tkg/packages/core/repo",
15:57:35      "status": "Reconcile succeeded",
15:57:35      "tag": "v1.23.8_vmware.2-tkg.1"
15:57:35    }
15:57:35  ]
15:57:35  $ tanzu package repository update carvel-test --url registry-svc.registry.svc.cluster.local:443/secret-test/test-repo@sha256:e07483e2140fa427d9875aee9055d72efc49a732f3a3fb2c9651d9f39159315a --namespace test-ns --create-namespace --create --wait=true --poll-interval 20s --poll-timeout 30s --kubeconfig /home/kubo/.kube/config 
15:57:57  
15:57:57  
15:57:57  Please consider using 'tanzu package repository update' to update the package repository with correct settings
```

### Release note

```release-note
Fix package plugin tests flakiness
```

### CODE REVIEW

**Review by codegold79 — APPROVED** [review]

File: cmd/cli/plugin/package/test/lib/package_plugin.go [hunk 1]
```diff
@@ -400,10 +400,7 @@ func (p *packagePlugin) CheckRepositoryAvailable(o *packagedatamodel.RepositoryO
 			RepositoryName: o.RepositoryName,
 			Namespace:      o.Namespace,
 		})
-		if result.Error != nil {
-			return false, result.Error
-		}
-		if result.Stdout != nil && strings.Contains(result.Stdout.String(), "Reconcile succeeded") {
+		if result.Error == nil && result.Stdout != nil && strings.Contains(result.Stdout.String(), "Reconcile succeeded") {
```
Comment (maralavi) [inline cmd/cli/plugin/package/test/lib/package_plugin.go:403]: Just to be clear, does this change mean we don't return an error on repository Get error as we want to retry and only return error on time out to success?

Comment (HL-EverGreen) [reply cmd/cli/plugin/package/test/lib/package_plugin.go:403]: Yeah.. Since we also want to retry in case of error (to let the test work on slow testbed), so no Get error will be returned except for timeout error.

Comment (HL-EverGreen) [reply cmd/cli/plugin/package/test/lib/package_plugin.go]: Hi @maralavi, I removed the retries here since we've already done a retry on packaging API availability [here](https://github.com/vmware-tanzu/tanzu-framework/blob/main/cmd/cli/plugin/package/test/package_plugin_integration_test.go#L491-L504). But this block doesn't guarantee that the packaging API is available after `kapp-controller` restarts. So I updated my fix to let this block ensure the `kapp-controller` finishes restart and the packaging API is available. Details can be seen at the description of this PR. Thanks

**Review by maralavi — APPROVED** [review]

File: cmd/cli/plugin/package/test/lib/package_plugin.go (hunk 1 above)
Comment (maralavi) [reply cmd/cli/plugin/package/test/lib/package_plugin.go]: I see. Thanks for the clarification :)
