### PR TITLE
Reverting tools dependency to v0.1.10

### LINKED ISSUE #3438: Fix linter issues in the cli modules
**Bug description**
A dependency of golangci-lint was causing linters to get skipped, and therefore the linters have not been run correctly for a while now. 
https://github.com/vmware-tanzu/tanzu-framework/pull/3433 has been submitted to fix the dependency issue, but this is throwing up a lot of linter errors

This issue is to track fixing the linter errors in the following modules
* https://github.com/vmware-tanzu/tanzu-framework/tree/main/cli/core
* https://github.com/vmware-tanzu/tanzu-framework/tree/main/cli/runtime
* https://github.com/vmware-tanzu/tanzu-framework/tree/main/cmd/cli/plugin/cluster

**Affected product area (please put an X in all that apply)**

- ( ) APIs
- ( ) Addons
- (X) CLI
- ( ) Docs
- ( ) IAM
- ( ) Installation
- (X) Plugin
- ( ) Security
- (X) Test and Release
- (X) User Experience
- ( ) Developer Experience

**Expected behavior**
The linters should not throw errors

**Steps to reproduce the bug**

**Version** (include the SHA if the version is not obvious)

**Environment where the bug was observed (cloud, OS, etc)**

**Relevant Debug Output (Logs, manifests, etc)**

### PR DESCRIPTION
**Pull request by saji-pivotal**
### What this PR does / why we need it
This PR attempts to fix linters getting short circuited because of an incompatible dependency version
This PR also fixes (or skips) linter issues in the following directories

```
cli/core
cli/runtime
cmd/cli/plugin/cluster
```
### Which issue(s) this PR fixes
Fixes #3438

### Describe testing done for PR
1. Ran the golangci-lint binary wherever possible locally
2. This PR relies on the linter checks that get run as part of the CI

### Release note

```release-note
Reverted the tools dependency to v0.1.10
Fixed or skipped linter issues
```

### CODE REVIEW

**Comment by vuil** [comment]
To see the full extent of the linter warnings, try applying this change to the toplevel Makefile temporarily to your PR:

```
-               $(GOLANGCI_LINT) run -v --timeout=10m || exit 1; \
+               $(GOLANGCI_LINT) run -v --timeout=10m; \
```

File: cli/core/pkg/command/config.go [hunk 1]
```diff
@@ -1,6 +1,7 @@
 // Copyright 2021 VMware, Inc. All Rights Reserved.
 // SPDX-License-Identifier: Apache-2.0
 
+//nolint:gocritic
```
Comment (anujc25) [inline cli/core/pkg/command/config.go:4]: Considering we are skipping the errors for the entire file, Which type of and how many linter errors we are trying to skip here?

File: cli/core/pkg/command/plugin_manager.go [hunk 2]
```diff
@@ -482,7 +483,7 @@ func getRepositories() *cli.MultiRepo {
 
 // getInstalledElseAvailablePluginVersion return installed plugin version if plugin is installed
 // if not installed it returns available recommanded plugin version
-func getInstalledElseAvailablePluginVersion(p plugin.Discovered) string {
+func getInstalledElseAvailablePluginVersion(p plugin.Discovered) string { // nolint:gocritic
```
Comment (anujc25) [inline cli/core/pkg/command/plugin_manager.go:486]: Can this linter error be easily solved by passing argument as a pointer instead of entire object? If yes, this might be really quick thing to fix if we can fix it quickly.

File: cli/core/pkg/pluginmanager/manager.go [hunk 3]
```diff
@@ -1,6 +1,7 @@
 // Copyright 2021 VMware, Inc. All Rights Reserved.
 // SPDX-License-Identifier: Apache-2.0
 
+//nolint:gocritic
```
Comment (anujc25) [inline cli/core/pkg/pluginmanager/manager.go:4]: Considering we are skipping the errors for the entire file, Which type of and how many linter errors we are trying to skip here?

File: cli/runtime/apis/config/v1alpha1/clientconfig.go [hunk 4]
```diff
@@ -1,6 +1,7 @@
 // Copyright 2021 VMware, Inc. All Rights Reserved.
 // SPDX-License-Identifier: Apache-2.0
 
+//nolint:gocritic
```
Comment (anujc25) [inline cli/runtime/apis/config/v1alpha1/clientconfig.go:4]: Considering we are skipping the errors for the entire file, Which type of and how many linter errors we are trying to skip here?

File: cli/runtime/apis/config/v1alpha1/clientconfig_types.go [hunk 5]
```diff
@@ -1,6 +1,7 @@
 // Copyright 2021 VMware, Inc. All Rights Reserved.
 // SPDX-License-Identifier: Apache-2.0
 
+//nolint:gocritic
```
Comment (anujc25) [inline cli/runtime/apis/config/v1alpha1/clientconfig_types.go:4]: Considering we are skipping the errors for the entire file, Which type of and how many linter errors we are trying to skip here?

File: cli/core/pkg/command/plugin_manager.go (hunk 2 above)
Comment (saji-pivotal) [reply cli/core/pkg/command/plugin_manager.go:486]: I've filed a story to fix a bunch of these linter errors en-masse - https://github.com/vmware-tanzu/tanzu-framework/issues/3470

**Comment by saji-pivotal** [comment]
@anujc25 I'm not sure on a per-file level how many linter errors we're skipping
I have filed the following issues to refactor the code, and actually fix the linter issues we're seeing

https://github.com/vmware-tanzu/tanzu-framework/issues/3470
https://github.com/vmware-tanzu/tanzu-framework/issues/3471

**Comment by anujc25** [comment]
Sounds good. This PR looks to me.

**Review by anujc25 — APPROVED** [review]
LGTM
