### PR TITLE
Fix error/warning displayed when CLIPlugin CRD is not installed with `tanzu plugin` commands

### LINKED ISSUE #1392: `tanzu plugin list` throws warning when talking to old management cluster not having CLIPlugin CRD
**Bug description**

When Tanzu CLI is used to talk with old management-cluster where the `CLIPlugin` CRD is not available, currently, it throws an error/warning message with each `tanzu plugin` command if current context is set for the user (meaning user is logged into the management cluster)

```sh
$ tanzu plugin list
I1215 11:42:45.096403   93795 request.go:665] Waited for 1.13822524s due to client-side throttling, not priority and fairness, request: GET:https://ps-az-mc-c846c100.westus2.cloudapp.azure.com:6443/apis/rbac.authorization.k8s.io/v1?timeout=32s
unable to discover server plugins, unable to list plugin from discovery 'default-ps-az-mc': failed to list *v1alpha1.CLIPluginList: no matches for kind "CLIPlugin" in version "cli.tanzu.vmware.com/v1alpha1"

  NAME                DESCRIPTION                                                        SCOPE       DISCOVERY  VERSION  STATUS
  login               Login to the platform                                              Standalone  default    v0.11.1  not installed
  management-cluster  Kubernetes management-cluster operations                           Standalone  default    v0.11.1  not installed
  package             Tanzu package management                                           Standalone  default    v0.11.1  not installed
  pinniped-auth       Pinniped authentication operations (usually not directly invoked)  Standalone  default    v0.11.1  not installed
  secret              Tanzu secret management                                            Standalone  default    v0.11.1  not installed
```

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [ ] Addons
- [x] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [x] User Experience

**Expected behavior**

Do not throw a warning/error message when talking to the old management cluster and show the result of the command.

**Steps to reproduce the bug**
1. log in to old management-cluster v1.4.0
2. run `tanzu plugin list`

**Version** (include the SHA if the version is not obvious)

**Environment where the bug was observed (cloud, OS, etc)**

**Relevant Debug Output (Logs, manifests, etc)**

### PR DESCRIPTION
**Pull request by anujc25**
### What this PR does / why we need it

- When Tanzu CLI is used to talk with old management-cluster where the
  CLIPlugin CRD is not available, currently, it throws an error/warning
  a message with each `tanzu plugin` command if a user is logged in to a
  cluster
- This change fixes the issue by verifying the presence of CRD before
  querying for available plugins

### Which issue(s) this PR fixes

Fixes #1392

### Describe testing done for PR
- Manual testing was done by testing the `tanzu plugin` command against v1.4.0 as well as v1.5.0 clusters.

### Release note

```release-note
Fix error/warning displayed when CLIPlugin CRD is not installed with `tanzu plugin` commands
```

### PR Checklist

- [x] Squash the commits into one or a small number of logical commits
      
- [x] Use good commit [messages](https://github.com/vmware-tanzu/tanzu-framework/blob/main/CONTRIBUTING.md)
- [x] Ensure PR contains terms all contributors can understand and links all contributors can access

### CODE REVIEW

File: pkg/v1/cli/discovery/kubernetes.go [hunk 1]
```diff
@@ -56,17 +56,28 @@ func (k *KubernetesDiscovery) Name() string {
...
+	return k.GetDiscoveredPlugins(clusterClient)
+}
+
+// GetDiscoveredPlugins returns the list of discovered plugin from a kubernetes cluster
+func (k *KubernetesDiscovery) GetDiscoveredPlugins(clusterClient clusterclient.Client) ([]plugin.Discovered, error) {
+	plugins := make([]plugin.Discovered, 0)
+
+	exists, err := clusterClient.VerifyCLIPluginCRD()
+	if !exists || err != nil {
+		// Skipping context-aware plugin discovery because CLIPlugin CRD not present on the cluster...
```
Comment (saji-pivotal) [inline pkg/v1/cli/discovery/kubernetes.go:77]: Should we log something to stdout and the skip?

File: pkg/v1/cli/discovery/kubernetes_test.go [hunk 2]
```diff
@@ -0,0 +1,100 @@
...
+var _ = Describe("Unit tests for kubernetes discovery", func() {
+	var (
+		err                  error
+		currentClusterClient *fakes.ClusterClient
+		kd                   *discovery.KubernetesDiscovery
+		plugins              []plugin.Discovered
+		cliplugins           []v1alpha1.CLIPlugin
+	)
+
+	Describe("When Getting Discovered plugins from k8s cluster", func() {
```
Comment (saji-pivotal) [inline pkg/v1/cli/discovery/kubernetes_test.go:34]: nit-ish: In all the tests, wouldn't it be more logical to have the `Expect(err).NotTo(HaveOccurred())` as the first check before the other checks?

File: pkg/v1/tkg/fakes/helper/fakeobjectcreater.go [hunk 3]
```diff
@@ -577,3 +578,17 @@ func GetFakePinnipedInfo(pinnipedInfo PinnipedInfo) string {
 	pinnipedInfoJSON = fmt.Sprintf(pinnipedInfoJSON, string(data))
 	return pinnipedInfoJSON
 }
+
+// NewCLIPlugin returns new MachineHealthCheck object
```
Comment (saji-pivotal) [inline pkg/v1/tkg/fakes/helper/fakeobjectcreater.go:582]: This seems to be a typo? NewCLIPlugin should return a new CLI plugin object?

File: pkg/v1/cli/discovery/kubernetes_test.go [hunk 4]
```diff
@@ -0,0 +1,100 @@
...
+		})
+		Context("When ListCLIPluginResources list of CLIPlugin resources", func() {
+			BeforeEach(func() {
+				cliplugin1 := fakehelper.NewCLIPlugin(fakehelper.TestCLIPluginOption{Name: "plugin1", Description: "plugin1 desc", RecommendedVersion: "v0.0.1"})
+				cliplugin2 := fakehelper.NewCLIPlugin(fakehelper.TestCLIPluginOption{Name: "plugin2", Description: "plugin2 desc", RecommendedVersion: "v0.0.2"})
+				cliplugins = append(cliplugins, cliplugin1, cliplugin2)
+				currentClusterClient.VerifyCLIPluginCRDReturns(true, nil)
+				currentClusterClient.ListCLIPluginResourcesReturns(cliplugins, nil)
+			})
+			It("return list of plugins without error", func() {
```
Comment (saji-pivotal) [inline pkg/v1/cli/discovery/kubernetes_test.go:90]: nit: It looks like we're returning an ordered list. Would it help to add that in the description of the test being run here? i.e `It("return ordered list...)`.

**Review by saji-pivotal — CHANGES_REQUESTED** [review]

**Review by saji-pivotal — APPROVED** [review]
Great work! LGTM from me, but I'd love it if we got another set of eyes on this

File: pkg/v1/cli/discovery/kubernetes.go [hunk 5]
```diff
@@ -56,17 +57,28 @@ func (k *KubernetesDiscovery) Name() string {
...
 
+	return k.GetDiscoveredPlugins(clusterClient)
+}
+
+// GetDiscoveredPlugins returns the list of discovered plugin from a kubernetes cluster
+func (k *KubernetesDiscovery) GetDiscoveredPlugins(clusterClient clusterclient.Client) ([]plugin.Discovered, error) {
+	plugins := make([]plugin.Discovered, 0)
+
+	exists, err := clusterClient.VerifyCLIPluginCRD()
+	if !exists || err != nil {
```
Comment (imikushin) [inline pkg/v1/cli/discovery/kubernetes.go:77]: **question**: Looks like we're swallowing `err`, is this intentional?

Comment (anujc25) [reply pkg/v1/cli/discovery/kubernetes.go:77]: Thanks for the catch. Not it's not intentional. Updated

**Review by vuil — APPROVED** [review]
Lgtm, thanks!
