### PR TITLE
Use TKR API commands based on feature-gate on the supervisor-cluster

### LINKED ISSUE #3040: `tanzu kubenetes-release` commands might show inconsistency with vSphere8 Supervisor because of v1alpha3 TKRs
**Bug description**
Currently, in the CLI to use TKR v1alpha3 we need to set feature-flag `features.global.tkr-version-v1alpha3-beta` to `true`  talking  with vSphere8 supervisor cluster.

Now, we do not expect the customers to configure this featureflag when talking with vsphere8 supervisor cluster we need to update the logic to dynamically determine the management-cluster and decide whether `v1alpha1` or `v1alpha3` TKR API based commands to invoke.

**Affected product area (please put an X in all that apply)**

- ( ) APIs
- ( ) Addons
- (x) CLI
- ( ) Docs
- ( ) IAM
- ( ) Installation
- ( ) Plugin
- ( ) Security
- ( ) Test and Release
- ( ) User Experience
- ( ) Developer Experience

**Expected behavior**
tanzu kubernetes-release commands to work as expected.

**Steps to reproduce the bug**

**Version** (include the SHA if the version is not obvious)

**Environment where the bug was observed (cloud, OS, etc)**

**Relevant Debug Output (Logs, manifests, etc)**

### PR DESCRIPTION
**Pull request by anujc25**
### What this PR does / why we need it
- Use TKR v1alpha3 API commands based on feature-gate on the supervisor-cluster
Signed-off-by: Anuj Chaudhari <anujc@vmware.com>

### Which issue(s) this PR fixes

Fixes #3040

### Describe testing done for PR
1. `tanzu login` to vSphere8 based supervisor cluster which has TKR v1alpha3 API
2. Disable the feature-flag `tanzu config set features.global.tkr-version-v1alpha3-beta false`
3. Get the TKRs
```
~ $ tanzu kr get
  NAME                                 VERSION                            COMPATIBLE  ACTIVE
  v1.22.8---vmware.1-tkg.2-zshippable  v1.22.8+vmware.1-tkg.2-zshippable  True        True
  v1.23.5---vmware.1-tkg.1-zshippable  v1.23.5+vmware.1-tkg.1-zshippable  True        True
```
4. Deactivate and activate TKRs to verify it is taking effect
```
~ $ tanzu kr deactivate v1.22.8---vmware.1-tkg.2-zshippable
Applying patch to resource v1.22.8---vmware.1-tkg.2-zshippable of type *v1alpha3.TanzuKubernetesRelease ...
```
```
~ $ tanzu kr get
  NAME                                 VERSION                            COMPATIBLE  ACTIVE
  v1.23.5---vmware.1-tkg.1-zshippable  v1.23.5+vmware.1-tkg.1-zshippable  True        True
```
```
~ $ tanzu kr activate v1.22.8---vmware.1-tkg.2-zshippable
Applying patch to resource v1.22.8---vmware.1-tkg.2-zshippable of type *v1alpha3.TanzuKubernetesRelease ...
```
```
~ $ tanzu kr get
  NAME                                 VERSION                            COMPATIBLE  ACTIVE
  v1.22.8---vmware.1-tkg.2-zshippable  v1.22.8+vmware.1-tkg.2-zshippable  True        True
  v1.23.5---vmware.1-tkg.1-zshippable  v1.23.5+vmware.1-tkg.1-zshippable  True        True
```

### Release note

```release-note
Use TKR v1alpha3 API commands based on feature-gate on the supervisor-cluster
```

### CODE REVIEW

**Review by prkalle — APPROVED** [review]
LGTM. Thanks for the fix!

File: pkg/v1/tkg/tkgctl/featuregate_helper.go [hunk 1]
```diff
@@ -40,14 +42,21 @@ func (fg *featureGateHelper) FeatureActivatedInNamespace(reqContext context.Cont
...
-		return fg.isTKCFeatureActivated(clusterClient, feature, namespace)
+	isPacific, err := clusterClient.IsPacificRegionalCluster()
+	if err != nil {
+		return false, errors.Wrap(err, "error determining Tanzu Kubernetes Cluster service for vSphere management cluster ")
+	}
+
+	if isPacific {
+		// If requested feature is `ClusterClassFeature` or `TKCAPIFeature` it gets decided on different criteria at the moment
+		// This is because we are unable to query Featuregates for the devops users on the TKGS clusters because of the permission restrictions
+		// TODO: Fix this logic to rely on actual featuregates once permission issue for the devops user has been resolved
```
Comment (saji-pivotal) [inline pkg/v1/tkg/tkgctl/featuregate_helper.go:53]: Q: Is there a GH issue for this TODO?

**Review by saji-pivotal — COMMENTED** [review]
@anujc25 Nice work overall! Are these changes unit-testable?

File: pkg/v1/tkg/tkgctl/featuregate_helper.go (hunk 1 above)
Comment (anujc25) [reply pkg/v1/tkg/tkgctl/featuregate_helper.go:53]: I have filled: https://github.com/vmware-tanzu/tanzu-framework/issues/3052

**Review by tenczar — APPROVED** [review]
LGTM

File: pkg/v1/tkg/tkgctl/featuregate_helper.go (hunk 1 above)
Comment (anujc25) [reply pkg/v1/tkg/tkgctl/featuregate_helper.go:53]: Unfortunately, it's kind of hard to write unit tests at this level of cobra commands but we have unit tests for internal functions being invoked here.

**Review by miclettej — APPROVED** [review]
