### PR TITLE
Fix the deletion of discovery sources by using DeleteCLIDiscoverySource API in tanzu plugin source delete command

### LINKED ISSUE #4055: Unable to delete a plugin source
**Bug description**

I am no longer able to delete a plugin source.

**Affected product area (please put an X in all that apply)**

- ( ) APIs
- ( ) Addons
- (x) CLI
- ( ) Docs
- ( ) IAM
- ( ) Installation
- ( ) Plugin
- ( ) Security
- ( ) Test and Release
- ( ) User Experience
- ( ) Developer Experience

**Expected behavior**

A plugin source should be properly deleted

**Steps to reproduce the bug**

```
tanzu plugin source list
  NAME     TYPE   SCOPE
  default  local  Standalone
tanzu plugin source add -n stage.25 -t oci -u projects-stg.registry.vmware.com/tkg/packages/standalone-plugins:v0.25.3-tf_vmware.1
✔  successfully added discovery source stage.25
tanzu plugin source list
  NAME      TYPE   SCOPE
  default   local  Standalone
  stage.25  oci    Standalone
tanzu plugin source delete stage.25
✔  deleted discovery source stage.25
tanzu plugin source list
  NAME      TYPE   SCOPE
  default   local  Standalone
  stage.25  oci    Standalone
```
Notice that the plugin source `stage.25` was not actually removed although right above it said it was.

**Version** (include the SHA if the version is not obvious)
Today's main: e0064860dab49ec9dc406d700078f2cea64fea78

**Environment where the bug was observed (cloud, OS, etc)**

Locally

**Relevant Debug Output (Logs, manifests, etc)**

### PR DESCRIPTION
**Pull request by mpanchajanya**
### What this PR does / why we need it

Fix the deletion of discovery sources.
Uses the Config API method `DeleteCLIDiscoverySource` instead of deprecated `StoreClientConfig`

### Which issue(s) this PR fixes

Fixes #4055 

### Describe testing done for PR

Unit Testing and Validate the `tanzu plugin source delete` command

```
mpanchajanya@mpanchajany-a01 tanzu-framework % tanzu config get                  
clientOptions:
    features:
        global:
            context-target: "false"
            context-aware-cli-for-plugins: "true"
            tkr-version-v1alpha3-beta: "false"
        management-cluster:
            dual-stack-ipv6-primary: "false"
            export-from-confirm: "true"
            import: "false"
            standalone-cluster-mode: "false"
            aws-instance-types-exclude-arm: "true"
            custom-nameservers: "false"
            dual-stack-ipv4-primary: "false"
        package:
            kctrl-package-command-tree: "true"
        cluster:
            dual-stack-ipv6-primary: "false"
            custom-nameservers: "false"
            dual-stack-ipv4-primary: "false"
    cli:
        discoverySources:
            - local:
                name: admin-local
                path: admin
            - local:
                name: default
                path: standalone
              contextType: k8s
        edition: tkg
        bomRepo: projects.registry.vmware.com/tkg
        compatibilityFilePath: tkg-compatibility
```

```
mpanchajanya@mpanchajany-a01 tanzu-framework % tanzu plugin source list
  NAME         TYPE   SCOPE       
  admin-local  local  Standalone  
  default      local  Standalone  
```

```
mpanchajanya@mpanchajany-a01 tanzu-framework % tanzu plugin source delete admin-local
✔  deleted discovery source admin-local
```

```
mpanchajanya@mpanchajany-a01 tanzu-framework % tanzu config get                      
clientOptions:
    features:
        global:
            context-target: "false"
            context-aware-cli-for-plugins: "true"
            tkr-version-v1alpha3-beta: "false"
        management-cluster:
            dual-stack-ipv6-primary: "false"
            export-from-confirm: "true"
            import: "false"
            standalone-cluster-mode: "false"
            aws-instance-types-exclude-arm: "true"
            custom-nameservers: "false"
            dual-stack-ipv4-primary: "false"
        package:
            kctrl-package-command-tree: "true"
        cluster:
            dual-stack-ipv6-primary: "false"
            custom-nameservers: "false"
            dual-stack-ipv4-primary: "false"
    cli:
        discoverySources:
            - local:
                name: default
                path: standalone
              contextType: k8s
        edition: tkg
        bomRepo: projects.registry.vmware.com/tkg
        compatibilityFilePath: tkg-compatibility
```

### CODE REVIEW

File: cli/runtime/config/cli_discovery_sources_test.go [hunk 1]
```diff
@@ -268,6 +268,7 @@ func TestDeleteCLIDiscoverySource(t *testing.T) {
 		src     *configapi.ClientConfig
 		input   string
 		deleted bool
```
Comment (vuil) [inline cli/runtime/config/cli_discovery_sources_test.go:270]: nit: I don't see .deleted getting used anywhere

File: cli/runtime/config/cli_discovery_sources_test.go [hunk 2]
```diff
@@ -339,9 +342,46 @@ func TestDeleteCLIDiscoverySource(t *testing.T) {
 					},
 				},
 			},
+			count:   1,
 			input:   "test",
```
Comment (vuil) [inline cli/runtime/config/cli_discovery_sources_test.go:346]: test2?

File: cli/runtime/config/cli_discovery_sources_test.go [hunk 3]
```diff
@@ -339,9 +342,46 @@ func TestDeleteCLIDiscoverySource(t *testing.T) {
...
+							{
+								Local: &configapi.LocalDiscovery{
+									Name: "default",
+									Path: "standalone",
+								},
+								ContextType: configapi.CtxTypeK8s,
+							},
+							{
+								Local: &configapi.LocalDiscovery{
+									Name: "admin-local",
```
Comment (vuil) [inline cli/runtime/config/cli_discovery_sources_test.go:372]: Looks like we support sources of same name of different discovery type? If so, would be good to include a test to verify the expected behavior when delete is issued on the name.

File: cli/core/pkg/command/discovery_source.go [hunk 4]
```diff
@@ -193,25 +193,7 @@ var deleteDiscoverySourceCmd = &cobra.Command{
...
-		}
-
-		newDiscoverySources, err := deleteDiscoverySource(cfg.ClientOptions.CLI.DiscoverySources, discoveryName)
-		if err != nil {
-			return err
-		}
-
-		cfg.ClientOptions.CLI.DiscoverySources = newDiscoverySources
-		err = configlib.StoreClientConfig(cfg)
+		err = configlib.DeleteCLIDiscoverySource(discoveryName)
```
Comment (vuil) [inline cli/core/pkg/command/discovery_source.go:196]: The intention is to support deleting the first matching source by name? If so it may be a good idea to add a comment to deleteCLIDiscoverySource near where getCLIDiscoverySource is called.

File: cli/runtime/config/cli_discovery_sources_test.go (hunk 3 above)
Comment (anujc25) [reply cli/runtime/config/cli_discovery_sources_test.go:372]: > Looks like we support sources of same name of different discovery type? 

I don't think we support this AFAIK.

File: cli/runtime/config/cli_discovery_sources_test.go (hunk 1 above)
Comment (mpanchajanya) [reply cli/runtime/config/cli_discovery_sources_test.go:270]: not needed I have used errStr for the same. removed `deleted`

File: cli/runtime/config/cli_discovery_sources_test.go (hunk 2 above)
Comment (mpanchajanya) [reply cli/runtime/config/cli_discovery_sources_test.go:346]: test case is valid description was misspelled. Corrected

File: cli/core/pkg/command/discovery_source.go (hunk 4 above)
Comment (mpanchajanya) [reply cli/core/pkg/command/discovery_source.go:196]: since discovery source are unique by name itself. There should only be one entry matching with the name.

File: cli/runtime/config/cli_discovery_sources_test.go (hunk 3 above)
Comment (mpanchajanya) [reply cli/runtime/config/cli_discovery_sources_test.go:368]: discovery source are unique by name itself; Cannot have same name for two different types. There should only be one entry matching with the name.

File: cli/core/pkg/command/discovery_source.go (hunk 4 above)
Comment (vuil) [reply cli/core/pkg/command/discovery_source.go:196]: So it is not intentional, but the code does not error out on config with multiple sources of the same name. Which is probably a not a bad thing, since it means the implementation can still be used to correct the discovery sources should the file somehow reach that state. 
I think it warrants at least a comment say at getCLIDiscoverySource that we are making an assumption that there should only be one source with the name, hence we are returning the first match.

Comment (mpanchajanya) [reply cli/core/pkg/command/discovery_source.go:203]: added the description on GetCLIDiscoverySource()

**Review by anujc25 — APPROVED** [review]
Looks good.
