### PR TITLE
vSphere upgrade rely on moid instead of name

### LINKED ISSUE #1396: Tanzu upgrade isn't idempotent on vSphere when VM template is moved/renamed
**Bug description**
The upgrade operation will trigger a repave of a cluster in the unlikely event that it is called after the VM template for the current version has been moved or renamed. 
**Affected product area (please put an X in all that apply)**

- [x] APIs
- [ ] Addons
- [ ] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Expected behavior**
The upgrade operation should remain idempotent when the VM template underlying the cluster is moved/renamed.

**Steps to reproduce the bug**
Create a cluster on vSphere. Move/rename the VM template the cluster was just created from and trigger and upgrade. This will cause the cluster's nodes to be repaved. 
**Version** (include the SHA if the version is not obvious)

**Environment where the bug was observed (cloud, OS, etc)**

**Relevant Debug Output (Logs, manifests, etc)**

### PR DESCRIPTION
**Pull request by tenczar**
This change updates the upgrade logic so that a change to the name(path)
of the virtual machine template does not cause VSphereMachineTemplates
to be regenerated.

### What this PR does / why we need it
It is possible that the upgrade operation will not be idempotent in vSphere clusters when the name/path of the VM template has changed. This PR updates this logic so that the VM template can be renamed without causing a repaving of the cluster.
### Which issue(s) this PR fixes

Fixes #1396 

### Describe testing done for PR
Added unit tests to verify new templates are only created when the vm moid changes. Tested upgrade in vcenter after changing vm template name. Verified that new machine templates were not generated

### Release note

```release-note
Fixes a rare issue where cluster machines would be incorrectly rotated when performing an upgrade where the only change to the cluster was the name or path of the VM template.
```

### PR Checklist

- [x] Squash the commits into one or a small number of logical commits
      
- [x] Use good commit [messages](https://github.com/vmware-tanzu/tanzu-framework/blob/main/CONTRIBUTING.md)
- [x] Ensure PR contains terms all contributors can understand and links all contributors can access

### CODE REVIEW

**Comment by vuil** [comment]
Thanks for the changes @tenczar . Please file an issue to description the problem and reference it in this PR. We will likely need to continue discussion there on the most appropriate way to address it.

File: pkg/v1/tkg/client/upgrade_cluster.go [hunk 1]
```diff
@@ -947,7 +949,7 @@ func isNewVSphereTemplateRequired(machineTemplate *capvv1beta1.VSphereMachineTem
 		return true
 	}
 	// If vm template given is the same as we already have in VSphereMachineTemplate
-	if machineTemplate.Spec.Template.Spec.Template != clusterUpgradeConfig.UpgradeComponentInfo.VSphereVMTemplateName {
```
Comment (vuil) [inline pkg/v1/tkg/client/upgrade_cluster.go:950]: two things:
- (nit) the comment does not match the code any more
- what happens when upgrading existing clusters that to not have this annotation set?

Comment (tenczar) [reply pkg/v1/tkg/client/upgrade_cluster.go:950]: > what happens when upgrading existing clusters that to not have this annotation set?
In this case a user presumably intends for an upgrade. For example, existing 1.5 clusters don't have this annotation. When a user performs an upgrade using the 1.6 cli they should be expecting an upgrade. This might trip up some main branch users immediately after this gets added to the tree, but for end users this upgrade should be expected.

**Comment by steven-zou** [comment]
@tenczar / @vuil 

When is this PR available?

**Review by anujc25 — APPROVED** [review]
Looks good

**Review by imikushin — APPROVED** [review]
LGTM
