### PR TITLE
Fix upgrade logic for additional packages in ClusterBoostrap but not in CBT

### LINKED ISSUE #3937: Packages are not upgraded if they are in clusterboostrap but not in clusterbootstrap template
**Bug description**
Packages are not upgraded if they are in clusterboostrap but not in clusterbootstrap template. There can be optional packages in clusterbootstrap but not present in clusterbootstrap template. They need to be upgraded if they are specified in TKr's spec.bootstrappackages

**Affected product area (please put an X in all that apply)**

- ( ) APIs
- (x) Addons
- ( ) CLI
- ( ) Docs
- ( ) IAM
- ( ) Installation
- ( ) Plugin
- ( ) Security
- ( ) Test and Release
- ( ) User Experience
- ( ) Developer Experience

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the SHA if the version is not obvious)

**Environment where the bug was observed (cloud, OS, etc)**

**Relevant Debug Output (Logs, manifests, etc)**

### PR DESCRIPTION
**Pull request by shyaamsn**
### What this PR does / why we need it
There might be additional packages in clusterbootstrap but not in clusterboostraptemplate. During upgrade these packages refName to be updated. The logic is to update the package refName if its present in tkr spec.bootstrappackages. If its not present then its the user's responsibility to fix them

### Which issue(s) this PR fixes

Fixes #3937 

### Describe testing done for PR
Unit test

### Release note

```release-note
Fix upgrade logic for additional packages in ClusterBoostrap but not in CBT
```

### CODE REVIEW

**Comment by alfredthenarwhal** [comment]
> @lubronzhan:  /test install-vc7
Commit: 609a855

Build failed! Build no: 3316

File: addons/controllers/clusterbootstrap_controller.go [hunk 1]
```diff
@@ -575,6 +574,21 @@ func (r *ClusterBootstrapReconciler) mergeClusterBootstrapPackagesWithTemplate(
...
+	}
+
+	// There might be packages in clusterbootstrap but not in clusterboostraptemplate.
+	// The below loop tries to find those packages and updates the RefName if it is found in tkr's spec.bootstrapPackages.
+	// If its not there in tkr's spec.bootstrappackages then user has to update the version of it in clusterbootstrap.
+	for additionalPkgRefName, additionalPkg := range additionalPackageMap {
+		if _, ok := additionalPackageTemplateMap[additionalPkgRefName]; !ok {
+			additionalPkgFromTKr, additionalPkgNamePrefix, err := util.GetBootstrapPackageNameFromTKR(r.context, r.Client, additionalPkg.RefName, cluster)
+			if err != nil {
+				log.Info(fmt.Sprintf("unable to find any additional bootstrap package prefixed with '%s' for ClusterBootstrap %s/%s in TKR", additionalPkgNamePrefix, cluster.Name, cluster.Namespace))
```
Comment (maralavi) [inline addons/controllers/clusterbootstrap_controller.go:587]: Seems like when error is returned on ```GetBootstrapPackageNameFromTKR```, it does not return prefix information any more. Not related to this PR but a bug with existing logic. Could you please modify the ```additionalPkgNamePrefix``` to return prefix even on error so that the log above can be useful?

Comment (maralavi) [reply addons/controllers/clusterbootstrap_controller.go:587]: Also I noticed in most places we log with this format & ordering ```<NAMESPACE>/<NAME>```. Could you please fix this in the log message above and in the other existing usage of ```GetBootstrapPackageNameFromTKR``` in the code to stay consistent?

File: addons/controllers/clusterbootstrap_controller.go [hunk 2]
```diff
@@ -575,6 +574,21 @@ func (r *ClusterBootstrapReconciler) mergeClusterBootstrapPackagesWithTemplate(
 			updatedClusterBootstrap.Spec.AdditionalPackages = append(updatedClusterBootstrap.Spec.AdditionalPackages, newPkg)
 			packages = append(packages, newPkg)
 		}
+		additionalPackageTemplateMap[packageRefName] = templatePkg
+	}
+
+	// There might be packages in clusterbootstrap but not in clusterboostraptemplate.
+	// The below loop tries to find those packages and updates the RefName if it is found in tkr's spec.bootstrapPackages.
+	// If its not there in tkr's spec.bootstrappackages then user has to update the version of it in clusterbootstrap.
```
Comment (maralavi) [inline addons/controllers/clusterbootstrap_controller.go:582]: If its not in tkr's ```bootstrappackages```, does it work if the user just update the version in ```clusterbootstrap```? Should we provide instructions on how? Wouldn't it immutable?

File: addons/controllers/clusterbootstrap_controller.go (hunk 1 above)
Comment (shyaamsn) [reply addons/controllers/clusterbootstrap_controller.go]: Fixed

File: addons/controllers/clusterbootstrap_controller.go (hunk 2 above)
Comment (shyaamsn) [reply addons/controllers/clusterbootstrap_controller.go:582]: I have added a testcase to update the version in clusterbootstrap and ensured it can work. I am not sure there is anything special to provide in documentation. It's just a matter of updating clusterbootstrap.spec.AdditionalPackages[index].RefName to updated version

**Review by lubronzhan — APPROVED** [review]

**Review by maralavi — APPROVED** [review]
