### PR TITLE
Fix bootstrap packages got deployed without their configuration 

### LINKED ISSUE #3144: Bootstrap packages got deployed without their configuration
## Background
The steps to deploy a bootstrap package to the target cluster are:
1. Every bootstrap package controller watches their bootstrap package cr (like CalicoConfig) and reconcile them, to generate `data-values secret` with the package configuration, and recorded this secret's name in bootstrap package cr’s `status.secretRef`

2. Bootstrap controller reconcile the bootstrap cr, load bootstrap packages inside, generate bootstrap packages’ `packageInstall` with the reference of `data-values secret` that recorded in bootstrap package cr’s `status.secretRef`

## Problem

Currently the steps above cannot be guaranteed to execute in order. Which means if step 2 happens before step 1, **the package is deployed without corresponding secret reference, and using default package configuration inside packages to install**.

Because the logic inside bootstrap controller treat empty `status.secretRef` as `no data values secret is needed for ClusterBootstrapPackage`.
https://github.com/vmware-tanzu/tanzu-framework/blob/d91e6d8f5e09737d1da14acbc4136bd0feb3acc8/addons/controllers/clusterbootstrap_controller.go#L962-L971

And probably after some time,  step 1 is finished and the bootstrap controller reconcile the bootstrap cr again, the correct configuration for packageInstall is updated.

But this basically violates the design and most of the e2e test scenarios. The `unconfigured package` should never be installed in the target cluster on any steps.

This problem was originally found in a flaky error https://github.com/vmware-tanzu/tanzu-framework/issues/3130 **CC based aws e2e test failure due to deleting a secret with no name** , when the cluster creation process is finished but the `data-values secret` does not exists in CalicoConfig's `status.secretRef`.

And by catching the calico packageInstall full content in this pr https://github.com/vmware-tanzu/tanzu-framework/pull/3142, we can see that the reconciled succeeded calico package has empty values fields `Values:[]`

```
Show the contents of PackageInstall github-1534-wc-v2vl-calico for package calico.tanzu.vmware.com of version 3.22.1+vmware.1-tkg.1-zshippable: ***TypeMeta:***Kind: APIVersion:*** ObjectMeta:***Name:github-1534-wc-v2vl-calico GenerateName: Namespace:tkg-system SelfLink: UID:ef371df4-608c-4718-b80b-e692dea53268 ResourceVersion:1573 Generation:1 CreationTimestamp:2022-08-16 08:14:58 +0000 UTC DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[] Annotations:map[tkg.tanzu.vmware.com/cluster-name:github-1534-wc-v2vl tkg.tanzu.vmware.com/cluster-namespace:tkg-system] OwnerReferences:[] Finalizers:[finalizers.packageinstall.packaging.carvel.dev/delete] ClusterName: ManagedFields:[***Manager:kapp-controller Operation:Update APIVersion:packaging.carvel.dev/v1alpha1 Time:2022-08-16 08:14:58 +0000 UTC FieldsType:FieldsV1 FieldsV1:***"f:metadata":***"f:finalizers":***".":***,"v:\"finalizers.packageinstall.packaging.carvel.dev/delete\"":*** Subresource:*** ***Manager:manager Operation:Update APIVersion:packaging.carvel.dev/v1alpha1 Time:2022-08-16 08:14:58 +0000 UTC FieldsType:FieldsV1 FieldsV1:***"f:metadata":***"f:annotations":***".":***,"f:tkg.tanzu.vmware.com/cluster-name":***,"f:tkg.tanzu.vmware.com/cluster-namespace":***,"f:spec":***".":***,"f:packageRef":***".":***,"f:refName":***,"f:versionSelection":***".":***,"f:constraints":***,"f:prereleases":***,"f:serviceAccountName":***,"f:syncPeriod":*** Subresource:*** ***Manager:kapp-controller Operation:Update APIVersion:packaging.carvel.dev/v1alpha1 Time:2022-08-16 08:15:53 +0000 UTC FieldsType:FieldsV1 FieldsV1:***"f:status":***".":***,"f:conditions":***,"f:friendlyDescription":***,"f:lastAttemptedVersion":***,"f:observedGeneration":***,"f:version":*** Subresource:status***]*** Spec:***ServiceAccountName:tanzu-cluster-bootstrap-sa Cluster:nil PackageRef:0xc0033831b8 Values:[] Paused:false Canceled:false SyncPeriod:&Duration***Duration:10m0s,*** NoopDelete:false*** Status:***GenericStatus:***ObservedGeneration:1 Conditions:[***Type:ReconcileSucceeded Status:True Reason: Message:***] FriendlyDescription:Reconcile succeeded UsefulErrorMessage:*** Version:3.22.1+vmware.1-tkg.1-zshippable LastAttemptedVersion:3.22.1+vmware.1-tkg.1-zshippable***

```

Ideally it should have something like below
```
values:
  - secretRef:
      name: github-1534-wc-v2vl-calico-data-values
```

**Affected product area (please put an X in all that apply)**

- ( ) APIs
- (x) Addons
- ( ) CLI
- ( ) Docs
- ( ) IAM
- (x) Installation
- ( ) Plugin
- ( ) Security
- (x) Test and Release
- (x) User Experience
- (x) Developer Experience

**Expected behavior**
Bootstrap packages got installed with their configuration secret.

**Steps to reproduce the bug**
Use this pr https://github.com/vmware-tanzu/tanzu-framework/pull/3142 for debuging the outputs on **TKG Integration Tests ClusterClass / TKG Integration Tests CAPA (ClusterClass)**

**Version** (include the SHA if the version is not obvious)
https://github.com/vmware-tanzu/tanzu-framework/commit/d91e6d8f5e09737d1da14acbc4136bd0feb3acc8

**Environment where the bug was observed (cloud, OS, etc)**
PR pipeline **TKG Integration Tests ClusterClass / TKG Integration Tests CAPA (ClusterClass)**

**Relevant Debug Output (Logs, manifests, etc)**
https://github.com/vmware-tanzu/tanzu-framework/runs/7852624454?check_suite_focus=true
Similar as the **TKG Integration Tests ClusterClass / TKG Integration Tests CAPA (ClusterClass)** result in https://github.com/vmware-tanzu/tanzu-framework/pull/3142

### PR DESCRIPTION
**Pull request by 12345lcr**
### What this PR does / why we need it
Skip the package installation when the package's value is from providerRef but the secret is not updated in the provider's status.

### Which issue(s) this PR fixes

Fixes https://github.com/vmware-tanzu/tanzu-framework/issues/3144 https://github.com/vmware-tanzu/tanzu-framework/issues/3130

### Describe testing done for PR

Modified ut to suit the case

### Release note

```release-note

```

### CODE REVIEW

**Comment by vijaykatam** [comment]
Thanks for the PR. I'll enqueue this to review tomorrow.

**Comment by 12345lcr** [comment]
Thanks @vijaykatam ! It seems that this pr also helped to fix the cc based CAPA calico e2e flaky issue https://github.com/vmware-tanzu/tanzu-framework/issues/3130. Since after this fix, the secretRef is guaranteed to exist in CalicoConfig's status as the test case expected. 

But still this took too long due to CalicoConfig controller not enqueue `Cluster` resources events. I will later create another pr to focus on this.

File: addons/controllers/clusterbootstrap_controller.go [hunk 1]
```diff
@@ -1211,8 +1211,11 @@ func (r *ClusterBootstrapReconciler) GetDataValueSecretNameFromBootstrapPackage(
 			if !found {
 				// In this case, we expect the secretRef to be present under status subresource and its value gets updated by
 				// the corresponding controller. However, the config controller might not create the secret in time.
-				r.Log.Info("provider status does not have secretRef", "GVR", gvr)
-				return "", nil
+				// Note that as long as the providerRef is defined, there is no such case that the final state of the secretRef remain not shown.
+				// So we return a error for this to wait and reconcile.
+				err = fmt.Errorf("provider %s does not have secretRef on its status", provider.GetName())
```
Comment (vijaykatam) [inline addons/controllers/clusterbootstrap_controller.go:1216]: This would block the controller from installing other packages which are ready to go which is not what we want. 

My proposal is to skip creating package install resource on a cluster if providerRef is not nil and secret is empty with an info log. Since we watch the provider resource, any update to status with a secretRef will enqueue the controller to reconcile the cluster and result in package install creation.

Comment (12345lcr) [reply addons/controllers/clusterbootstrap_controller.go:1216]: https://github.com/vmware-tanzu/tanzu-framework/blob/e4b205fcb028028f1b0df014e4bdf52b96f48245/addons/controllers/clusterbootstrap_controller.go#L1256-L1271

Hi Vijay, thanks for the comment. Based on my understanding, the ClusterBootstrap controller only watches events for tkr, ClusterBootstrap, and Secrets, but no provider resources. If we do not throw an error to enqueue again when providerRef is not nil and secret is empty, there might be a situation that the provider controller done creating the secret but not finished updating the secretRef on status, the secret creation event will trigger an ClusterBootstrap controller to enqueue but nothing happened due to the secretRef on provider's status is empty.

Unless we add all provider resources to ClusterBootstrap controller watch resources?

Comment (vijaykatam) [reply addons/controllers/clusterbootstrap_controller.go:1216]: Providers are watched separately since they are dynamic and can come and go based on new addon providers. See https://github.com/vmware-tanzu/tanzu-framework/blob/main/addons/controllers/clusterbootstrap_controller.go#L1084

Comment (12345lcr) [reply addons/controllers/clusterbootstrap_controller.go:1216]: Hi @vijaykatam , thanks for pointing this out. I found that this dynamic watch is for additional packages only. Core packages providers like AntreaConfig, CalicoConfig, VSphereCPIConfig, KappControllerConfig, and VSphereCSIConfig are not included, am I right?
https://github.com/vmware-tanzu/tanzu-framework/blob/ada7554ccee6eb06f19592d57ef5a9472e50b67f/addons/controllers/clusterbootstrap_controller.go#L260-L276

Comment (vijaykatam) [reply addons/controllers/clusterbootstrap_controller.go:1216]: Good catch. I thought we were(perhaps a regression in our refactor). I am fixing it [here](https://github.com/vmware-tanzu/tanzu-framework/pull/3440) with tests.

**Comment by 12345lcr** [comment]
Hi @vijaykatam , I have updated the pr to skip creating package install resource on a cluster if providerRef is not nil and secret is empty with an info log, but not blocking other packages to install. Please feel free to review again, thanks!

**Review by jeffwubj — APPROVED** [review]

**Comment by vijaykatam** [comment]
Sorry my feedback is delayed but the change looks good.
