### PR TITLE
validate workload cluster existence

### LINKED ISSUE #2988: CLI does not validate workload cluster existence for tkgs use case
**Bug description**
CLI command `tanzu cluster create` to create tkgs workload cluster, does not validate whether the workload cluster already exists or not, and if exists its failing at tkgs supervisor with a misleading error message 
**Affected product area (please put an X in all that apply)**

- ( ) APIs
- ( ) Addons
- (x) CLI
- ( ) Docs
- ( ) IAM
- ( ) Installation
- ( ) Plugin
- ( ) Security
- ( ) Test and Release
- ( ) User Experience
- ( ) Developer Experience

**Expected behavior**
CLI should validate the given input cluster name already exists or not, if exists throw error and fail-fast.
**Steps to reproduce the bug**
- Create a tkgs workload cluster
- Create a tkgs workload cluster with same name as in previous step
**Version** (include the SHA if the version is not obvious)

**Environment where the bug was observed (cloud, OS, etc)**

**Relevant Debug Output (Logs, manifests, etc)**

### PR DESCRIPTION
**Pull request by chandrareddyp**
### What this PR does / why we need it
For CLI command `tanzu cluster create`, validates whether the given input workload cluster name already exists or not, if exists then throws error

### Which issue(s) this PR fixes

Fixes #2988 

### Describe testing done for PR

- Unit Test cases
- Tested to create tkgs workload cluster which already exists
- Tested to create tkgs workload cluster which is already not exists

### Release note

```release-note
Fixes to validate workload cluster existence and throws an error if exists
```

### CODE REVIEW

File: pkg/v1/tkg/tkgctl/get_cluster.go [hunk 1]
```diff
@@ -57,3 +57,19 @@ func (t *tkgctl) GetClusters(options ListTKGClustersOptions) ([]client.ClusterIn
...
+func (t *tkgctl) IsClusterExists(clustername, namespace string) (bool, error) {
+	clusters, err := t.GetClusters(ListTKGClustersOptions{
+		Namespace: namespace,
+		IncludeMC: true,
+	})
+	if err != nil {
+		return false, err
+	}
+	for _, cluster := range clusters {
+		if cluster.Name == clustername && cluster.Namespace == namespace {
```
Comment (anujc25) [inline pkg/v1/tkg/tkgctl/get_cluster.go:70]: Just noticed that we have updated condition to also check the `namespace` as well. Previously we were just checking the cluster name irrespective of the namespace.

**Review by anujc25 — APPROVED** [review]
Looks good.

Please Add the `Release Notes` as part of PR description.

File: pkg/v1/tkg/tkgctl/get_cluster.go (hunk 1 above)
Comment (chandrareddyp) [reply pkg/v1/tkg/tkgctl/get_cluster.go:70]: okay, thanks.
