### PR TITLE
Fix Question mark prompt color

### LINKED ISSUE #292: Question mark prompt color
**Bug description**

The [styleguide](https://github.com/vmware-tanzu/tanzu-framework/blob/main/docs/cli/style_guide.md#color) calls for question prompts in cyan (informational), currently they are showing up green (success)

example:
screenshot of cli output showing a cyan question mark

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [ ] Addons
- [x] CLI
- [ ] Docs
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [x] User Experience

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the SHA if the version is not obvious)

**Environment where the bug was observed (cloud, OS, etc)**

**Relevant Debug Output (Logs, manifests, etc)**

### PR DESCRIPTION
**Pull request by mpanchajanya**
### What this PR does / why we need it

Fix the Question mark prompt color as per style guide and refactor the code to use survey pkg directly.

### Which issue(s) this PR fixes

Fixes #292 

### Describe testing done for PR

Screen Shot 2022-08-23 at 22 22 02

### Release note

```release-note
Any component using prompt.go will have the question mark color changed from green to cyan.

```

### CODE REVIEW

**Comment by marckhouzam** [comment]
Hi @mpanchajanya.  Could you explain why there is a refactoring of using the survey package?  I haven't looked at the code, but it would help me to understand the reason behind the refactoring.  Thanks 👍

**Comment by anujc25** [comment]
@mpanchajanya We should continue to use component library for this functionality and fix things in the `component` package itself rather than updating it in individual plugins. Another reason to continue use `component` package is that, not all plugins are developed within this repository but plugin developers uses this `component` package as part of plugin development.

**Comment by anujc25** [comment]
@mpanchajanya can you add screenshots or sample output of how prompt looks like with the recent change as part of PR description under `Describe testing done for PR` section.

**Review by marckhouzam — APPROVED** [review]
LGTM

Nice work @mpanchajanya

**Review by anujc25 — APPROVED** [review]
Changes looks good.

@mpanchajanya can you please fill release note section as well in the PR description?

File: pkg/v1/cli/component/prompt_test.go [hunk 1]
```diff
@@ -66,3 +66,17 @@ func Test_translatePromptConfig_Input(t *testing.T) {
...
+	assert := assert.New(t)
+
+	options := defaultPromptOptions()
+	opts := translatePromptOpts(options)
+
+	assert.NotNil(options)
+	assert.NotNil(opts)
+	assert.Equal("?", options.Icons.Question.Text)
+	assert.Equal("cyan+b", options.Icons.Question.Format)
+	assert.Equal(2, len(opts))
```
Comment (marckhouzam) [inline pkg/v1/cli/component/prompt_test.go:80]: I think it would be a good test to make sure that that `translatePromptOpts()` does not miss any fields.
I think you could create an empty `AskOptions` variable and apply both `opts` to it and then make sure the contents match what is expected.

**Review by marckhouzam — COMMENTED** [review]
Great that you added a test!
