### PR TITLE
setting vsphere csi replica count based on controlplane node count

### LINKED ISSUE #2117: VSphereCSIConfigController should set deployment replicas based on control plane node count
**Bug description**
vsphere-csi controller replicas is static which can lead to issues during upgrade of cluster.

Deployment replicas should be set based on control plane count so that scale up/scale down of control plane nodes results in vsphere-csi controller replicas equal to control plane nodes.

Requirements
1. Minimum of one replica
2. Max 3 replicas if control plane node count >=3

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [x] Addons
- [ ] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

### PR DESCRIPTION
**Pull request by peterochodo**
### What this PR does / why we need it
- we should set the vsphere csi replica count based on control plane node count

### Which issue(s) this PR fixes
Fixes #2117 

### Describe testing done for PR
- env test runs have verified that vsphere-csi count is now based on control-plane count

### Release note

```release-note
package-based-lcm: set vsphere csi replica count based on controlplane node count
```

### PR Checklist

- [ ] Squash the commits into one or a small number of logical commits
      
- [ ] Use good commit [messages](https://github.com/vmware-tanzu/tanzu-framework/blob/main/CONTRIBUTING.md)
- [ ] Ensure PR contains terms all contributors can understand and links all contributors can access

### CODE REVIEW

File: addons/controllers/csi/vspherecsiconfig_utils.go [hunk 1]
```diff
@@ -326,3 +332,49 @@ func (r *VSphereCSIConfigReconciler) overrideMiscValues(dvscsi *DataValuesVSpher
 		dvscsi.InsecureFlag = *config.InsecureFlag
 	}
 }
+
+func (r *VSphereCSIConfigReconciler) constrainNumberOfDeploymentReplicas(ctx context.Context, proposedCount int) int {
```
Comment (danniel1205) [inline addons/controllers/csi/vspherecsiconfig_utils.go:336]: Suggestion: wondering if things would be easier to do `proposedCount int32` return `int32` as well? So that caller does not have to do several conversions.

Comment (peterochodo) [reply addons/controllers/csi/vspherecsiconfig_utils.go]: updated

**Review by danniel1205 — APPROVED** [review]
lgtm
