### PR TITLE
Fix package plugin tests for classy clusters

### LINKED ISSUE #4209: Package plugin integration test fails with Calico CNI
**Bug description**

#4138 has broken package plugin integration test. It fails consistently with the following error:

```
Validating the pre-requisites...
Failure [2.369 seconds]
[BeforeSuite] BeforeSuite 
/datadrive/tanzu/actions-runner/_work/tanzu-framework/tanzu-framework/cmd/cli/plugin/package/test/package_plugin_integration_test.go:149

Unexpected error:
      <*errors.fundamental | 0xc00071a4b0>: {
          msg: "Calico management-cluster creation is forbidden...",
          stack: [0x285b7d5, 0x28624be, 0xaed011, 0xaeca05, 0xaed546, 0xb0f82b, 0xb0f30f, 0xb116f2, 0xb1c629, 0xb1c44a, 0x286d2a5, 0x524162, 0x46da21],
      }
      Calico management-cluster creation is forbidden...
  occurred
``` 

This needs to be fixed to unblock CI.

**Affected product area (please put an X in all that apply)**

- ( ) APIs
- ( ) Addons
- ( ) CLI
- ( ) Docs
- ( ) IAM
- ( ) Installation
- ( ) Plugin
- ( ) Security
- (x) Test and Release
- ( ) User Experience
- ( ) Developer Experience

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the SHA if the version is not obvious)

**Environment where the bug was observed (cloud, OS, etc)**

**Relevant Debug Output (Logs, manifests, etc)**

### PR DESCRIPTION
**Pull request by shyaamsn**
### What this PR does / why we need it
Fix package plugin tests for classy clusters. Classy clusters use packageInstall CR on management cluster for installing kapp-controller on workload cluster. Legacy clusters use App CR on management cluster for installing kapp-controller on workload cluster. In the test we were pausing App before patching kapp-controller configmap but in Classy clusters this was getting overridden since PackageInstall CR is not paused. This change makes sure to check if packageinstall is found then pause packageinstall else pause app. 

### Which issue(s) this PR fixes
Fixes #4209 

### Describe testing done for PR
Ran the test on a classy and legacy cluster and it passes

### Release note

```release-note
Fix package plugin tests for classy clusters
```

### CODE REVIEW

File: cmd/cli/plugin/package/test/package_plugin_integration_test.go [hunk 1]
```diff
@@ -610,12 +628,33 @@ func pauseKappControllerPackage(clusterName, clusterNamespace, mgmtClusterKubeco
...
+	)
+
 	command := exec.NewCommand(
 		exec.WithCommand("kubectl"),
-		exec.WithArgs("patch", "app", fmt.Sprintf("%s-kapp-controller", clusterName), "-n", clusterNamespace, "--type", "merge", "-p", fmt.Sprintf("{\"spec\":{\"paused\":%t}}", pause), "--context", mgmtClusterKubeCtx, "--kubeconfig", mgmtClusterKubeconfigPath),
+		exec.WithArgs("get", "packageinstall", fmt.Sprintf("%s-kapp-controller", clusterName), "-n", clusterNamespace, "--context", mgmtClusterKubeCtx, "--kubeconfig", mgmtClusterKubeconfigPath),
 		exec.WithStdout(GinkgoWriter),
 	)
 	err := command.RunAndRedirectOutput(context.Background())
+	if err == nil {
```
Comment (maralavi) [inline cmd/cli/plugin/package/test/package_plugin_integration_test.go:642]: What if the error be something other than NotFound?

Comment (shyaamsn) [reply cmd/cli/plugin/package/test/package_plugin_integration_test.go:642]: Unfortunately the error returned by RunAndRedirectOutput is errors.WithStack and it doesnt return the actual error string. So cannot distinguish between NotFound and other error. The likelihood of other error happening is small as well as this is test code. So I think we can live with this for now and try to enhance it later.

Comment (praveenrewar) [reply cmd/cli/plugin/package/test/package_plugin_integration_test.go:640]: Since we have added the hack to create legacy clusters, maybe we can just skip adding this logic to check for PackageInstall or App for now?

Comment (maralavi) [reply cmd/cli/plugin/package/test/package_plugin_integration_test.go:640]: > Unfortunately the error returned by RunAndRedirectOutput is errors.WithStack and it doesnt return the actual error string. So cannot distinguish between NotFound and other error. The likelihood of other error happening is small as well as this is test code. So I think we can live with this for now and try to enhance it later.

I see, thanks for the clarification

**Review by maralavi — APPROVED** [review]

File: cmd/cli/plugin/package/test/package_plugin_integration_test.go (hunk 1 above)
Comment (shyaamsn) [reply cmd/cli/plugin/package/test/package_plugin_integration_test.go:641]: > Since we have added the hack to create legacy clusters, maybe we can just skip adding this logic to check for PackageInstall or App for now?

Downstream tests run on classy clusters. So need to add this logic for packageinstall as well as app.

**Review by rajathagasthya — APPROVED** [review]
